// Copyright information
// File originally from https://github.com/JeffG05/emoji_picker

final Map<String, int> wechatEmojis = Map.fromIterables([
  "GRINNING FACE WITH SMILING EYES",
  "FACE WITH TEARS OF JOY",
  "SMILING FACE WITH OPEN MOUTH",
  "SMILING FACE WITH OPEN MOUTH AND SMILING EYES",
  "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT",
  "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES",
  "WINKING FACE",
  "SMILING FACE WITH SMILING EYES",
  "FACE SAVOURING DELICIOUS FOOD",
  "RELIEVED FACE",
  "SMILING FACE WITH HEART-SHAPED EYES",
  "SMIRKING FACE",
  "UNAMUSED FACE",
  "FACE WITH COLD SWEAT",
  "PENSIVE FACE",
  "CONFOUNDED FACE",
  "FACE THROWING A KISS",
  "KISSING FACE WITH CLOSED EYES",
  "FACE WITH STUCK-OUT TONGUE AND WINKING EYE",
  "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES",
  "DISAPPOINTED FACE",
  "ANGRY FACE",
  "POUTING FACE",
  "CRYING FACE",
  "PERSEVERING FACE",
  "FACE WITH LOOK OF TRIUMPH",
  "DISAPPOINTED BUT RELIEVED FACE",
  "FEARFUL FACE",
  "WEARY FACE",
  "SLEEPY FACE",
  "TIRED FACE",
  "LOUDLY CRYING FACE",
  "FACE WITH OPEN MOUTH AND COLD SWEAT",
  "FACE SCREAMING IN FEAR",
  "ASTONISHED FACE",
  "FLUSHED FACE",
  "DIZZY FACE",
  "FACE WITH MEDICAL MASK",
  "GRINNING CAT FACE WITH SMILING EYES",
  "CAT FACE WITH TEARS OF JOY",
  "SMILING CAT FACE WITH OPEN MOUTH",
  "SMILING CAT FACE WITH HEART-SHAPED EYES",
  "CAT FACE WITH WRY SMILE",
  "KISSING CAT FACE WITH CLOSED EYES",
  "POUTING CAT FACE",
  "CRYING CAT FACE",
  "WEARY CAT FACE",
  "FACE WITH NO GOOD GESTURE",
  "FACE WITH OK GESTURE",
  "PERSON BOWING DEEPLY",
  "SEE-NO-EVIL MONKEY",
  "HEAR-NO-EVIL MONKEY",
  "SPEAK-NO-EVIL MONKEY",
  "HAPPY PERSON RAISING ONE HAND",
  "PERSON RAISING BOTH HANDS IN CELEBRATION",
  "PERSON FROWNING",
  "PERSON WITH POUTING FACE",
  "PERSON WITH FOLDED HANDS",
  "BLACK SCISSORS",
  "WHITE HEAVY CHECK MARK",
  "AIRPLANE",
  "ENVELOPE",
  "RAISED FIST",
  "RAISED HAND",
  "VICTORY HAND",
  "PENCIL",
  "BLACK NIB",
  "HEAVY CHECK MARK",
  "HEAVY MULTIPLICATION X",
  "SPARKLES",
  "EIGHT SPOKED ASTERISK",
  "EIGHT POINTED BLACK STAR",
  "SNOWFLAKE",
  "SPARKLE",
  "CROSS MARK",
  "NEGATIVE SQUARED CROSS MARK",
  "BLACK QUESTION MARK ORNAMENT",
  "WHITE QUESTION MARK ORNAMENT",
  "WHITE EXCLAMATION MARK ORNAMENT",
  "HEAVY EXCLAMATION MARK SYMBOL",
  "HEAVY BLACK HEART",
  "HEAVY PLUS SIGN",
  "HEAVY MINUS SIGN",
  "HEAVY DIVISION SIGN",
  "BLACK RIGHTWARDS ARROW",
  "CURLY LOOP",
  "ROCKET",
  "RAILWAY CAR",
  "HIGH-SPEED TRAIN",
  "HIGH-SPEED TRAIN WITH BULLET NOSE",
  "METRO",
  "STATION",
  "BUS",
  "BUS STOP",
  "AMBULANCE",
  "FIRE ENGINE",
  "POLICE CAR",
  "TAXI",
  "AUTOMOBILE",
  "RECREATIONAL VEHICLE",
  "DELIVERY TRUCK",
  "SHIP",
  "SPEEDBOAT",
  "HORIZONTAL TRAFFIC LIGHT",
  "CONSTRUCTION SIGN",
  "POLICE CARS REVOLVING LIGHT",
  "TRIANGULAR FLAG ON POST",
  "DOOR",
  "NO ENTRY SIGN",
  "SMOKING SYMBOL",
  "NO SMOKING SYMBOL",
  "BICYCLE",
  "PEDESTRIAN",
  "MENS SYMBOL",
  "WOMENS SYMBOL",
  "RESTROOM",
  "BABY SYMBOL",
  "TOILET",
  "WATER CLOSET",
  "BATH",
  "CIRCLED LATIN CAPITAL LETTER M",
  "NEGATIVE SQUARED LATIN CAPITAL LETTER A",
  "NEGATIVE SQUARED LATIN CAPITAL LETTER B",
  "NEGATIVE SQUARED LATIN CAPITAL LETTER O",
  "NEGATIVE SQUARED LATIN CAPITAL LETTER P",
  "NEGATIVE SQUARED AB",
  "SQUARED CL",
  "SQUARED COOL",
  "SQUARED FREE",
  "SQUARED ID",
  "SQUARED NEW",
  "SQUARED NG",
  "SQUARED OK",
  "SQUARED SOS",
  "SQUARED UP WITH EXCLAMATION MARK",
  "SQUARED VS",
  "SQUARED KATAKANA KOKO",
  "SQUARED KATAKANA SA",
  "SQUARED CJK UNIFIED IDEOGRAPH-7121",
  "SQUARED CJK UNIFIED IDEOGRAPH-6307",
  "SQUARED CJK UNIFIED IDEOGRAPH-7981",
  "SQUARED CJK UNIFIED IDEOGRAPH-7A7A",
  "SQUARED CJK UNIFIED IDEOGRAPH-5408",
  "SQUARED CJK UNIFIED IDEOGRAPH-6E80",
  "SQUARED CJK UNIFIED IDEOGRAPH-6709",
  "SQUARED CJK UNIFIED IDEOGRAPH-6708",
  "SQUARED CJK UNIFIED IDEOGRAPH-7533",
  "SQUARED CJK UNIFIED IDEOGRAPH-5272",
  "SQUARED CJK UNIFIED IDEOGRAPH-55B6",
  "CIRCLED IDEOGRAPH ADVANTAGE",
  "CIRCLED IDEOGRAPH ACCEPT",
  "COPYRIGHT SIGN",
  "REGISTERED SIGN",
  "DOUBLE EXCLAMATION MARK",
  "EXCLAMATION QUESTION MARK",
  "TRADE MARK SIGN",
  "INFORMATION SOURCE",
  "LEFT RIGHT ARROW",
  "UP DOWN ARROW",
  "NORTH WEST ARROW",
  "NORTH EAST ARROW",
  "SOUTH EAST ARROW",
  "SOUTH WEST ARROW",
  "LEFTWARDS ARROW WITH HOOK",
  "RIGHTWARDS ARROW WITH HOOK",
  "WATCH",
  "HOURGLASS",
  "BLACK RIGHT-POINTING DOUBLE TRIANGLE",
  "BLACK LEFT-POINTING DOUBLE TRIANGLE",
  "BLACK UP-POINTING DOUBLE TRIANGLE",
  "BLACK DOWN-POINTING DOUBLE TRIANGLE",
  "ALARM CLOCK",
  "HOURGLASS WITH FLOWING SAND",
  "BLACK SMALL SQUARE",
  "WHITE SMALL SQUARE",
  "BLACK RIGHT-POINTING TRIANGLE",
  "BLACK LEFT-POINTING TRIANGLE",
  "WHITE MEDIUM SQUARE",
  "BLACK MEDIUM SQUARE",
  "WHITE MEDIUM SMALL SQUARE",
  "BLACK MEDIUM SMALL SQUARE",
  "BLACK SUN WITH RAYS",
  "CLOUD",
  "BLACK TELEPHONE",
  "BALLOT BOX WITH CHECK",
  "UMBRELLA WITH RAIN DROPS",
  "HOT BEVERAGE",
  "WHITE UP POINTING INDEX",
  "WHITE SMILING FACE",
  "ARIES",
  "TAURUS",
  "GEMINI",
  "CANCER",
  "LEO",
  "VIRGO",
  "LIBRA",
  "SCORPIUS",
  "SAGITTARIUS",
  "CAPRICORN",
  "AQUARIUS",
  "PISCES",
  "BLACK SPADE SUIT",
  "BLACK CLUB SUIT",
  "BLACK HEART SUIT",
  "BLACK DIAMOND SUIT",
  "HOT SPRINGS",
  "BLACK UNIVERSAL RECYCLING SYMBOL",
  "WHEELCHAIR SYMBOL",
  "ANCHOR",
  "WARNING SIGN",
  "HIGH VOLTAGE SIGN",
  "MEDIUM WHITE CIRCLE",
  "MEDIUM BLACK CIRCLE",
  "SOCCER BALL",
  "BASEBALL",
  "SNOWMAN WITHOUT SNOW",
  "SUN BEHIND CLOUD",
  "OPHIUCHUS",
  "NO ENTRY",
  "CHURCH",
  "FOUNTAIN",
  "FLAG IN HOLE",
  "SAILBOAT",
  "TENT",
  "FUEL PUMP",
  "ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS",
  "ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS",
  "LEFTWARDS BLACK ARROW",
  "UPWARDS BLACK ARROW",
  "DOWNWARDS BLACK ARROW",
  "BLACK LARGE SQUARE",
  "WHITE LARGE SQUARE",
  "WHITE MEDIUM STAR",
  "HEAVY LARGE CIRCLE",
  "WAVY DASH",
  "PART ALTERNATION MARK",
  "CIRCLED IDEOGRAPH CONGRATULATION",
  "CIRCLED IDEOGRAPH SECRET",
  "MAHJONG TILE RED DRAGON",
  "PLAYING CARD BLACK JOKER",
  "CYCLONE",
  "FOGGY",
  "CLOSED UMBRELLA",
  "NIGHT WITH STARS",
  "SUNRISE OVER MOUNTAINS",
  "SUNRISE",
  "CITYSCAPE AT DUSK",
  "SUNSET OVER BUILDINGS",
  "RAINBOW",
  "BRIDGE AT NIGHT",
  "WATER WAVE",
  "VOLCANO",
  "MILKY WAY",
  "EARTH GLOBE ASIA-AUSTRALIA",
  "NEW MOON SYMBOL",
  "FIRST QUARTER MOON SYMBOL",
  "WAXING GIBBOUS MOON SYMBOL",
  "FULL MOON SYMBOL",
  "CRESCENT MOON",
  "FIRST QUARTER MOON WITH FACE",
  "GLOWING STAR",
  "SHOOTING STAR",
  "CHESTNUT",
  "SEEDLING",
  "PALM TREE",
  "CACTUS",
  "TULIP",
  "CHERRY BLOSSOM",
  "ROSE",
  "HIBISCUS",
  "SUNFLOWER",
  "BLOSSOM",
  "EAR OF MAIZE",
  "EAR OF RICE",
  "HERB",
  "FOUR LEAF CLOVER",
  "MAPLE LEAF",
  "FALLEN LEAF",
  "LEAF FLUTTERING IN WIND",
  "MUSHROOM",
  "TOMATO",
  "AUBERGINE",
  "GRAPES",
  "MELON",
  "WATERMELON",
  "TANGERINE",
  "BANANA",
  "PINEAPPLE",
  "RED APPLE",
  "GREEN APPLE",
  "PEACH",
  "CHERRIES",
  "STRAWBERRY",
  "HAMBURGER",
  "SLICE OF PIZZA",
  "MEAT ON BONE",
  "POULTRY LEG",
  "RICE CRACKER",
  "RICE BALL",
  "COOKED RICE",
  "CURRY AND RICE",
  "STEAMING BOWL",
  "SPAGHETTI",
  "BREAD",
  "FRENCH FRIES",
  "ROASTED SWEET POTATO",
  "DANGO",
  "ODEN",
  "SUSHI",
  "FRIED SHRIMP",
  "FISH CAKE WITH SWIRL DESIGN",
  "SOFT ICE CREAM",
  "SHAVED ICE",
  "ICE CREAM",
  "DOUGHNUT",
  "COOKIE",
  "CHOCOLATE BAR",
  "CANDY",
  "LOLLIPOP",
  "CUSTARD",
  "HONEY POT",
  "SHORTCAKE",
  "BENTO BOX",
  "POT OF FOOD",
  "COOKING",
  "FORK AND KNIFE",
  "TEACUP WITHOUT HANDLE",
  "SAKE BOTTLE AND CUP",
  "WINE GLASS",
  "COCKTAIL GLASS",
  "TROPICAL DRINK",
  "BEER MUG",
  "CLINKING BEER MUGS",
  "RIBBON",
  "WRAPPED PRESENT",
  "BIRTHDAY CAKE",
  "JACK-O-LANTERN",
  "CHRISTMAS TREE",
  "FATHER CHRISTMAS",
  "FIREWORKS",
  "FIREWORK SPARKLER",
  "BALLOON",
  "PARTY POPPER",
  "CONFETTI BALL",
  "TANABATA TREE",
  "CROSSED FLAGS",
  "PINE DECORATION",
  "JAPANESE DOLLS",
  "CARP STREAMER",
  "WIND CHIME",
  "MOON VIEWING CEREMONY",
  "SCHOOL SATCHEL",
  "GRADUATION CAP",
  "CAROUSEL HORSE",
  "FERRIS WHEEL",
  "ROLLER COASTER",
  "FISHING POLE AND FISH",
  "MICROPHONE",
  "MOVIE CAMERA",
  "CINEMA",
  "HEADPHONE",
  "ARTIST PALETTE",
  "TOP HAT",
  "CIRCUS TENT",
  "TICKET",
  "CLAPPER BOARD",
  "PERFORMING ARTS",
  "VIDEO GAME",
  "DIRECT HIT",
  "SLOT MACHINE",
  "BILLIARDS",
  "GAME DIE",
  "BOWLING",
  "FLOWER PLAYING CARDS",
  "MUSICAL NOTE",
  "MULTIPLE MUSICAL NOTES",
  "SAXOPHONE",
  "GUITAR",
  "MUSICAL KEYBOARD",
  "TRUMPET",
  "VIOLIN",
  "MUSICAL SCORE",
  "RUNNING SHIRT WITH SASH",
  "TENNIS RACQUET AND BALL",
  "SKI AND SKI BOOT",
  "BASKETBALL AND HOOP",
  "CHEQUERED FLAG",
  "SNOWBOARDER",
  "RUNNER",
  "SURFER",
  "TROPHY",
  "AMERICAN FOOTBALL",
  "SWIMMER",
  "HOUSE BUILDING",
  "HOUSE WITH GARDEN",
  "OFFICE BUILDING",
  "JAPANESE POST OFFICE",
  "HOSPITAL",
  "BANK",
  "AUTOMATED TELLER MACHINE",
  "HOTEL",
  "LOVE HOTEL",
  "CONVENIENCE STORE",
  "SCHOOL",
  "DEPARTMENT STORE",
  "FACTORY",
  "IZAKAYA LANTERN",
  "JAPANESE CASTLE",
  "EUROPEAN CASTLE",
  "SNAIL",
  "SNAKE",
  "HORSE",
  "SHEEP",
  "MONKEY",
  "CHICKEN",
  "BOAR",
  "ELEPHANT",
  "OCTOPUS",
  "SPIRAL SHELL",
  "BUG",
  "ANT",
  "HONEYBEE",
  "LADY BEETLE",
  "FISH",
  "TROPICAL FISH",
  "BLOWFISH",
  "TURTLE",
  "HATCHING CHICK",
  "BABY CHICK",
  "FRONT-FACING BABY CHICK",
  "BIRD",
  "PENGUIN",
  "KOALA",
  "POODLE",
  "BACTRIAN CAMEL",
  "DOLPHIN",
  "MOUSE FACE",
  "COW FACE",
  "TIGER FACE",
  "RABBIT FACE",
  "CAT FACE",
  "DRAGON FACE",
  "SPOUTING WHALE",
  "HORSE FACE",
  "MONKEY FACE",
  "DOG FACE",
  "PIG FACE",
  "FROG FACE",
  "HAMSTER FACE",
  "WOLF FACE",
  "BEAR FACE",
  "PANDA FACE",
  "PIG NOSE",
  "PAW PRINTS",
  "EYES",
  "EAR",
  "NOSE",
  "MOUTH",
  "TONGUE",
  "WHITE UP POINTING BACKHAND INDEX",
  "WHITE DOWN POINTING BACKHAND INDEX",
  "WHITE LEFT POINTING BACKHAND INDEX",
  "WHITE RIGHT POINTING BACKHAND INDEX",
  "FISTED HAND SIGN",
  "WAVING HAND SIGN",
  "OK HAND SIGN",
  "THUMBS UP SIGN",
  "THUMBS DOWN SIGN",
  "CLAPPING HANDS SIGN",
  "OPEN HANDS SIGN",
  "CROWN",
  "WOMANS HAT",
  "EYEGLASSES",
  "NECKTIE",
  "T-SHIRT",
  "JEANS",
  "DRESS",
  "KIMONO",
  "BIKINI",
  "WOMANS CLOTHES",
  "PURSE",
  "HANDBAG",
  "POUCH",
  "MANS SHOE",
  "ATHLETIC SHOE",
  "HIGH-HEELED SHOE",
  "WOMANS SANDAL",
  "WOMANS BOOTS",
  "FOOTPRINTS",
  "BUST IN SILHOUETTE",
  "BOY",
  "GIRL",
  "MAN",
  "WOMAN",
  "FAMILY",
  "MAN AND WOMAN HOLDING HANDS",
  "POLICE OFFICER",
  "WOMAN WITH BUNNY EARS",
  "BRIDE WITH VEIL",
  "PERSON WITH BLOND HAIR",
  "MAN WITH GUA PI MAO",
  "MAN WITH TURBAN",
  "OLDER MAN",
  "OLDER WOMAN",
  "BABY",
  "CONSTRUCTION WORKER",
  "PRINCESS",
  "JAPANESE OGRE",
  "JAPANESE GOBLIN",
  "GHOST",
  "BABY ANGEL",
  "EXTRATERRESTRIAL ALIEN",
  "ALIEN MONSTER",
  "IMP",
  "SKULL",
  "INFORMATION DESK PERSON",
  "GUARDSMAN",
  "DANCER",
  "LIPSTICK",
  "NAIL POLISH",
  "FACE MASSAGE",
  "HAIRCUT",
  "BARBER POLE",
  "SYRINGE",
  "PILL",
  "KISS MARK",
  "LOVE LETTER",
  "RING",
  "GEM STONE",
  "KISS",
  "BOUQUET",
  "COUPLE WITH HEART",
  "WEDDING",
  "BEATING HEART",
  "BROKEN HEART",
  "TWO HEARTS",
  "SPARKLING HEART",
  "GROWING HEART",
  "HEART WITH ARROW",
  "BLUE HEART",
  "GREEN HEART",
  "YELLOW HEART",
  "PURPLE HEART",
  "HEART WITH RIBBON",
  "REVOLVING HEARTS",
  "HEART DECORATION",
  "DIAMOND SHAPE WITH A DOT INSIDE",
  "ELECTRIC LIGHT BULB",
  "ANGER SYMBOL",
  "BOMB",
  "SLEEPING SYMBOL",
  "COLLISION SYMBOL",
  "SPLASHING SWEAT SYMBOL",
  "DROPLET",
  "DASH SYMBOL",
  "PILE OF POO",
  "FLEXED BICEPS",
  "DIZZY SYMBOL",
  "SPEECH BALLOON",
  "WHITE FLOWER",
  "HUNDRED POINTS SYMBOL",
  "MONEY BAG",
  "CURRENCY EXCHANGE",
  "HEAVY DOLLAR SIGN",
  "CREDIT CARD",
  "BANKNOTE WITH YEN SIGN",
  "BANKNOTE WITH DOLLAR SIGN",
  "MONEY WITH WINGS",
  "CHART WITH UPWARDS TREND AND YEN SIGN",
  "SEAT",
  "PERSONAL COMPUTER",
  "BRIEFCASE",
  "MINIDISC",
  "FLOPPY DISK",
  "OPTICAL DISC",
  "DVD",
  "FILE FOLDER",
  "OPEN FILE FOLDER",
  "PAGE WITH CURL",
  "PAGE FACING UP",
  "CALENDAR",
  "TEAR-OFF CALENDAR",
  "CARD INDEX",
  "CHART WITH UPWARDS TREND",
  "CHART WITH DOWNWARDS TREND",
  "BAR CHART",
  "CLIPBOARD",
  "PUSHPIN",
  "ROUND PUSHPIN",
  "PAPERCLIP",
  "STRAIGHT RULER",
  "TRIANGULAR RULER",
  "BOOKMARK TABS",
  "LEDGER",
  "NOTEBOOK",
  "NOTEBOOK WITH DECORATIVE COVER",
  "CLOSED BOOK",
  "OPEN BOOK",
  "GREEN BOOK",
  "BLUE BOOK",
  "ORANGE BOOK",
  "BOOKS",
  "NAME BADGE",
  "SCROLL",
  "MEMO",
  "TELEPHONE RECEIVER",
  "PAGER",
  "FAX MACHINE",
  "SATELLITE ANTENNA",
  "PUBLIC ADDRESS LOUDSPEAKER",
  "CHEERING MEGAPHONE",
  "OUTBOX TRAY",
  "INBOX TRAY",
  "PACKAGE",
  "E-MAIL SYMBOL",
  "INCOMING ENVELOPE",
  "ENVELOPE WITH DOWNWARDS ARROW ABOVE",
  "CLOSED MAILBOX WITH LOWERED FLAG",
  "CLOSED MAILBOX WITH RAISED FLAG",
  "POSTBOX",
  "NEWSPAPER",
  "MOBILE PHONE",
  "MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT",
  "VIBRATION MODE",
  "MOBILE PHONE OFF",
  "ANTENNA WITH BARS",
  "CAMERA",
  "VIDEO CAMERA",
  "TELEVISION",
  "RADIO",
  "VIDEOCASSETTE",
  "CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS",
  "SPEAKER WITH THREE SOUND WAVES",
  "BATTERY",
  "ELECTRIC PLUG",
  "LEFT-POINTING MAGNIFYING GLASS",
  "RIGHT-POINTING MAGNIFYING GLASS",
  "LOCK WITH INK PEN",
  "CLOSED LOCK WITH KEY",
  "KEY",
  "LOCK",
  "OPEN LOCK",
  "BELL",
  "BOOKMARK",
  "LINK SYMBOL",
  "RADIO BUTTON",
  "BACK WITH LEFTWARDS ARROW ABOVE",
  "END WITH LEFTWARDS ARROW ABOVE",
  "ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE",
  "SOON WITH RIGHTWARDS ARROW ABOVE",
  "TOP WITH UPWARDS ARROW ABOVE",
  "NO ONE UNDER EIGHTEEN SYMBOL",
  "KEYCAP TEN",
  "INPUT SYMBOL FOR LATIN CAPITAL LETTERS",
  "INPUT SYMBOL FOR LATIN SMALL LETTERS",
  "INPUT SYMBOL FOR NUMBERS",
  "INPUT SYMBOL FOR SYMBOLS",
  "INPUT SYMBOL FOR LATIN LETTERS",
  "FIRE",
  "ELECTRIC TORCH",
  "WRENCH",
  "HAMMER",
  "NUT AND BOLT",
  "HOCHO",
  "PISTOL",
  "CRYSTAL BALL",
  "SIX POINTED STAR WITH MIDDLE DOT",
  "JAPANESE SYMBOL FOR BEGINNER",
  "TRIDENT EMBLEM",
  "BLACK SQUARE BUTTON",
  "WHITE SQUARE BUTTON",
  "LARGE RED CIRCLE",
  "LARGE BLUE CIRCLE",
  "LARGE ORANGE DIAMOND",
  "LARGE BLUE DIAMOND",
  "SMALL ORANGE DIAMOND",
  "SMALL BLUE DIAMOND",
  "UP-POINTING RED TRIANGLE",
  "DOWN-POINTING RED TRIANGLE",
  "UP-POINTING SMALL RED TRIANGLE",
  "DOWN-POINTING SMALL RED TRIANGLE",
  "CLOCK FACE ONE OCLOCK",
  "CLOCK FACE TWO OCLOCK",
  "CLOCK FACE THREE OCLOCK",
  "CLOCK FACE FOUR OCLOCK",
  "CLOCK FACE FIVE OCLOCK",
  "CLOCK FACE SIX OCLOCK",
  "CLOCK FACE SEVEN OCLOCK",
  "CLOCK FACE EIGHT OCLOCK",
  "CLOCK FACE NINE OCLOCK",
  "CLOCK FACE TEN OCLOCK",
  "CLOCK FACE ELEVEN OCLOCK",
  "CLOCK FACE TWELVE OCLOCK",
  "MOUNT FUJI",
  "TOKYO TOWER",
  "STATUE OF LIBERTY",
  "SILHOUETTE OF JAPAN",
  "MOYAI",
  "GRINNING FACE",
  "SMILING FACE WITH HALO",
  "SMILING FACE WITH HORNS",
  "SMILING FACE WITH SUNGLASSES",
  "NEUTRAL FACE",
  "EXPRESSIONLESS FACE",
  "CONFUSED FACE",
  "KISSING FACE",
  "KISSING FACE WITH SMILING EYES",
  "FACE WITH STUCK-OUT TONGUE",
  "WORRIED FACE",
  "FROWNING FACE WITH OPEN MOUTH",
  "ANGUISHED FACE",
  "GRIMACING FACE",
  "FACE WITH OPEN MOUTH",
  "HUSHED FACE",
  "SLEEPING FACE",
  "FACE WITHOUT MOUTH",
  "HELICOPTER",
  "STEAM LOCOMOTIVE",
  "TRAIN",
  "LIGHT RAIL",
  "TRAM",
  "ONCOMING BUS",
  "TROLLEYBUS",
  "MINIBUS",
  "ONCOMING POLICE CAR",
  "ONCOMING TAXI",
  "ONCOMING AUTOMOBILE",
  "ARTICULATED LORRY",
  "TRACTOR",
  "MONORAIL",
  "MOUNTAIN RAILWAY",
  "SUSPENSION RAILWAY",
  "MOUNTAIN CABLEWAY",
  "AERIAL TRAMWAY",
  "ROWBOAT",
  "VERTICAL TRAFFIC LIGHT",
  "PUT LITTER IN ITS PLACE SYMBOL",
  "DO NOT LITTER SYMBOL",
  "POTABLE WATER SYMBOL",
  "NON-POTABLE WATER SYMBOL",
  "NO BICYCLES",
  "BICYCLIST",
  "MOUNTAIN BICYCLIST",
  "NO PEDESTRIANS",
  "CHILDREN CROSSING",
  "SHOWER",
  "BATHTUB",
  "PASSPORT CONTROL",
  "CUSTOMS",
  "BAGGAGE CLAIM",
  "LEFT LUGGAGE",
  "EARTH GLOBE EUROPE-AFRICA",
  "EARTH GLOBE AMERICAS",
  "GLOBE WITH MERIDIANS",
  "WAXING CRESCENT MOON SYMBOL",
  "WANING GIBBOUS MOON SYMBOL",
  "LAST QUARTER MOON SYMBOL",
  "WANING CRESCENT MOON SYMBOL",
  "NEW MOON WITH FACE",
  "LAST QUARTER MOON WITH FACE",
  "FULL MOON WITH FACE",
  "SUN WITH FACE",
  "EVERGREEN TREE",
  "DECIDUOUS TREE",
  "LEMON",
  "PEAR",
  "BABY BOTTLE",
  "HORSE RACING",
  "RUGBY FOOTBALL",
  "EUROPEAN POST OFFICE",
  "RAT",
  "MOUSE",
  "OX",
  "WATER BUFFALO",
  "COW",
  "TIGER",
  "LEOPARD",
  "RABBIT",
  "CAT",
  "DRAGON",
  "CROCODILE",
  "WHALE",
  "RAM",
  "GOAT",
  "ROOSTER",
  "DOG",
  "PIG",
  "DROMEDARY CAMEL",
  "BUSTS IN SILHOUETTE",
  "TWO MEN HOLDING HANDS",
  "TWO WOMEN HOLDING HANDS",
  "THOUGHT BALLOON",
  "BANKNOTE WITH EURO SIGN",
  "BANKNOTE WITH POUND SIGN",
  "OPEN MAILBOX WITH RAISED FLAG",
  "OPEN MAILBOX WITH LOWERED FLAG",
  "POSTAL HORN",
  "NO MOBILE PHONES",
  "TWISTED RIGHTWARDS ARROWS",
  "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS",
  "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY",
  "ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS",
  "LOW BRIGHTNESS SYMBOL",
  "HIGH BRIGHTNESS SYMBOL",
  "SPEAKER WITH CANCELLATION STROKE",
  "SPEAKER WITH ONE SOUND WAVE",
  "BELL WITH CANCELLATION STROKE",
  "MICROSCOPE",
  "TELESCOPE",
  "CLOCK FACE ONE-THIRTY",
  "CLOCK FACE TWO-THIRTY",
  "CLOCK FACE THREE-THIRTY",
  "CLOCK FACE FOUR-THIRTY",
  "CLOCK FACE FIVE-THIRTY",
  "CLOCK FACE SIX-THIRTY",
  "CLOCK FACE SEVEN-THIRTY",
  "CLOCK FACE EIGHT-THIRTY",
  "CLOCK FACE NINE-THIRTY",
  "CLOCK FACE TEN-THIRTY",
  "CLOCK FACE ELEVEN-THIRTY",
  "CLOCK FACE TWELVE-THIRTY"
],[
  128513,
  128514,
  128515,
  128516,
  128517,
  128518,
  128521,
  128522,
  128523,
  128524,
  128525,
  128527,
  128530,
  128531,
  128532,
  128534,
  128536,
  128538,
  128540,
  128541,
  128542,
  128544,
  128545,
  128546,
  128547,
  128548,
  128549,
  128552,
  128553,
  128554,
  128555,
  128557,
  128560,
  128561,
  128562,
  128563,
  128565,
  128567,
  128568,
  128569,
  128570,
  128571,
  128572,
  128573,
  128574,
  128575,
  128576,
  128581,
  128582,
  128583,
  128584,
  128585,
  128586,
  128587,
  128588,
  128589,
  128590,
  128591,
  9986,
  9989,
  9992,
  9993,
  9994,
  9995,
  9996,
  9999,
  10002,
  10004,
  10006,
  10024,
  10035,
  10036,
  10052,
  10055,
  10060,
  10062,
  10067,
  10068,
  10069,
  10071,
  10084,
  10133,
  10134,
  10135,
  10145,
  10160,
  128640,
  128643,
  128644,
  128645,
  128647,
  128649,
  128652,
  128655,
  128657,
  128658,
  128659,
  128661,
  128663,
  128665,
  128666,
  128674,
  128676,
  128677,
  128679,
  128680,
  128681,
  128682,
  128683,
  128684,
  128685,
  128690,
  128694,
  128697,
  128698,
  128699,
  128700,
  128701,
  128702,
  128704,
  9410,
  127344,
  127345,
  127358,
  127359,
  127374,
  127377,
  127378,
  127379,
  127380,
  127381,
  127382,
  127383,
  127384,
  127385,
  127386,
  127489,
  127490,
  127514,
  127535,
  127538,
  127539,
  127540,
  127541,
  127542,
  127543,
  127544,
  127545,
  127546,
  127568,
  127569,
  169,
  174,
  8252,
  8265,
  8482,
  8505,
  8596,
  8597,
  8598,
  8599,
  8600,
  8601,
  8617,
  8618,
  8986,
  8987,
  9193,
  9194,
  9195,
  9196,
  9200,
  9203,
  9642,
  9643,
  9654,
  9664,
  9723,
  9724,
  9725,
  9726,
  9728,
  9729,
  9742,
  9745,
  9748,
  9749,
  9757,
  9786,
  9800,
  9801,
  9802,
  9803,
  9804,
  9805,
  9806,
  9807,
  9808,
  9809,
  9810,
  9811,
  9824,
  9827,
  9829,
  9830,
  9832,
  9851,
  9855,
  9875,
  9888,
  9889,
  9898,
  9899,
  9917,
  9918,
  9924,
  9925,
  9934,
  9940,
  9962,
  9970,
  9971,
  9973,
  9978,
  9981,
  10548,
  10549,
  11013,
  11014,
  11015,
  11035,
  11036,
  11088,
  11093,
  12336,
  12349,
  12951,
  12953,
  126980,
  127183,
  127744,
  127745,
  127746,
  127747,
  127748,
  127749,
  127750,
  127751,
  127752,
  127753,
  127754,
  127755,
  127756,
  127759,
  127761,
  127763,
  127764,
  127765,
  127769,
  127771,
  127775,
  127776,
  127792,
  127793,
  127796,
  127797,
  127799,
  127800,
  127801,
  127802,
  127803,
  127804,
  127805,
  127806,
  127807,
  127808,
  127809,
  127810,
  127811,
  127812,
  127813,
  127814,
  127815,
  127816,
  127817,
  127818,
  127820,
  127821,
  127822,
  127823,
  127825,
  127826,
  127827,
  127828,
  127829,
  127830,
  127831,
  127832,
  127833,
  127834,
  127835,
  127836,
  127837,
  127838,
  127839,
  127840,
  127841,
  127842,
  127843,
  127844,
  127845,
  127846,
  127847,
  127848,
  127849,
  127850,
  127851,
  127852,
  127853,
  127854,
  127855,
  127856,
  127857,
  127858,
  127859,
  127860,
  127861,
  127862,
  127863,
  127864,
  127865,
  127866,
  127867,
  127872,
  127873,
  127874,
  127875,
  127876,
  127877,
  127878,
  127879,
  127880,
  127881,
  127882,
  127883,
  127884,
  127885,
  127886,
  127887,
  127888,
  127889,
  127890,
  127891,
  127904,
  127905,
  127906,
  127907,
  127908,
  127909,
  127910,
  127911,
  127912,
  127913,
  127914,
  127915,
  127916,
  127917,
  127918,
  127919,
  127920,
  127921,
  127922,
  127923,
  127924,
  127925,
  127926,
  127927,
  127928,
  127929,
  127930,
  127931,
  127932,
  127933,
  127934,
  127935,
  127936,
  127937,
  127938,
  127939,
  127940,
  127942,
  127944,
  127946,
  127968,
  127969,
  127970,
  127971,
  127973,
  127974,
  127975,
  127976,
  127977,
  127978,
  127979,
  127980,
  127981,
  127982,
  127983,
  127984,
  128012,
  128013,
  128014,
  128017,
  128018,
  128020,
  128023,
  128024,
  128025,
  128026,
  128027,
  128028,
  128029,
  128030,
  128031,
  128032,
  128033,
  128034,
  128035,
  128036,
  128037,
  128038,
  128039,
  128040,
  128041,
  128043,
  128044,
  128045,
  128046,
  128047,
  128048,
  128049,
  128050,
  128051,
  128052,
  128053,
  128054,
  128055,
  128056,
  128057,
  128058,
  128059,
  128060,
  128061,
  128062,
  128064,
  128066,
  128067,
  128068,
  128069,
  128070,
  128071,
  128072,
  128073,
  128074,
  128075,
  128076,
  128077,
  128078,
  128079,
  128080,
  128081,
  128082,
  128083,
  128084,
  128085,
  128086,
  128087,
  128088,
  128089,
  128090,
  128091,
  128092,
  128093,
  128094,
  128095,
  128096,
  128097,
  128098,
  128099,
  128100,
  128102,
  128103,
  128104,
  128105,
  128106,
  128107,
  128110,
  128111,
  128112,
  128113,
  128114,
  128115,
  128116,
  128117,
  128118,
  128119,
  128120,
  128121,
  128122,
  128123,
  128124,
  128125,
  128126,
  128127,
  128128,
  128129,
  128130,
  128131,
  128132,
  128133,
  128134,
  128135,
  128136,
  128137,
  128138,
  128139,
  128140,
  128141,
  128142,
  128143,
  128144,
  128145,
  128146,
  128147,
  128148,
  128149,
  128150,
  128151,
  128152,
  128153,
  128154,
  128155,
  128156,
  128157,
  128158,
  128159,
  128160,
  128161,
  128162,
  128163,
  128164,
  128165,
  128166,
  128167,
  128168,
  128169,
  128170,
  128171,
  128172,
  128174,
  128175,
  128176,
  128177,
  128178,
  128179,
  128180,
  128181,
  128184,
  128185,
  128186,
  128187,
  128188,
  128189,
  128190,
  128191,
  128192,
  128193,
  128194,
  128195,
  128196,
  128197,
  128198,
  128199,
  128200,
  128201,
  128202,
  128203,
  128204,
  128205,
  128206,
  128207,
  128208,
  128209,
  128210,
  128211,
  128212,
  128213,
  128214,
  128215,
  128216,
  128217,
  128218,
  128219,
  128220,
  128221,
  128222,
  128223,
  128224,
  128225,
  128226,
  128227,
  128228,
  128229,
  128230,
  128231,
  128232,
  128233,
  128234,
  128235,
  128238,
  128240,
  128241,
  128242,
  128243,
  128244,
  128246,
  128247,
  128249,
  128250,
  128251,
  128252,
  128259,
  128266,
  128267,
  128268,
  128269,
  128270,
  128271,
  128272,
  128273,
  128274,
  128275,
  128276,
  128278,
  128279,
  128280,
  128281,
  128282,
  128283,
  128284,
  128285,
  128286,
  128287,
  128288,
  128289,
  128290,
  128291,
  128292,
  128293,
  128294,
  128295,
  128296,
  128297,
  128298,
  128299,
  128302,
  128303,
  128304,
  128305,
  128306,
  128307,
  128308,
  128309,
  128310,
  128311,
  128312,
  128313,
  128314,
  128315,
  128316,
  128317,
  128336,
  128337,
  128338,
  128339,
  128340,
  128341,
  128342,
  128343,
  128344,
  128345,
  128346,
  128347,
  128507,
  128508,
  128509,
  128510,
  128511,
  128512,
  128519,
  128520,
  128526,
  128528,
  128529,
  128533,
  128535,
  128537,
  128539,
  128543,
  128550,
  128551,
  128556,
  128558,
  128559,
  128564,
  128566,
  128641,
  128642,
  128646,
  128648,
  128650,
  128653,
  128654,
  128656,
  128660,
  128662,
  128664,
  128667,
  128668,
  128669,
  128670,
  128671,
  128672,
  128673,
  128675,
  128678,
  128686,
  128687,
  128688,
  128689,
  128691,
  128692,
  128693,
  128695,
  128696,
  128703,
  128705,
  128706,
  128707,
  128708,
  128709,
  127757,
  127758,
  127760,
  127762,
  127766,
  127767,
  127768,
  127770,
  127772,
  127773,
  127774,
  127794,
  127795,
  127819,
  127824,
  127868,
  127943,
  127945,
  127972,
  128000,
  128001,
  128002,
  128003,
  128004,
  128005,
  128006,
  128007,
  128008,
  128009,
  128010,
  128011,
  128015,
  128016,
  128019,
  128021,
  128022,
  128042,
  128101,
  128108,
  128109,
  128173,
  128182,
  128183,
  128236,
  128237,
  128239,
  128245,
  128256,
  128257,
  128258,
  128260,
  128261,
  128262,
  128263,
  128265,
  128277,
  128300,
  128301,
  128348,
  128349,
  128350,
  128351,
  128352,
  128353,
  128354,
  128355,
  128356,
  128357,
  128358,
  128359
]);


/// Map of all possible emojis along with their names in [Category.SMILEYS]
final Map<String, String> smileys = Map.fromIterables([
  'Grinning Face',
  'Grinning Face With Big Eyes',
  'Grinning Face With Smiling Eyes',
  'Beaming Face With Smiling Eyes',
  'Grinning Squinting Face',
  'Grinning Face With Sweat',
  'Rolling on the Floor Laughing',
  'Face With Tears of Joy',
  'Slightly Smiling Face',
  'Upside-Down Face',
  'Winking Face',
  'Smiling Face With Smiling Eyes',
  'Smiling Face With Halo',
  'Smiling Face With Hearts',
  'Smiling Face With Heart-Eyes',
  'Star-Struck',
  'Face Blowing a Kiss',
  'Kissing Face',
  'Smiling Face',
  'Kissing Face With Closed Eyes',
  'Kissing Face With Smiling Eyes',
  'Face Savoring Food',
  'Face With Tongue',
  'Winking Face With Tongue',
  'Zany Face',
  'Squinting Face With Tongue',
  'Money-Mouth Face',
  'Hugging Face',
  'Face With Hand Over Mouth',
  'Shushing Face',
  'Thinking Face',
  'Zipper-Mouth Face',
  'Face With Raised Eyebrow',
  'Neutral Face',
  'Expressionless Face',
  'Face Without Mouth',
  'Smirking Face',
  'Unamused Face',
  'Face With Rolling Eyes',
  'Grimacing Face',
  'Lying Face',
  'Relieved Face',
  'Pensive Face',
  'Sleepy Face',
  'Drooling Face',
  'Sleeping Face',
  'Face With Medical Mask',
  'Face With Thermometer',
  'Face With Head-Bandage',
  'Nauseated Face',
  'Face Vomiting',
  'Sneezing Face',
  'Hot Face',
  'Cold Face',
  'Woozy Face',
  'Dizzy Face',
  'Exploding Head',
  'Cowboy Hat Face',
  'Partying Face',
  'Smiling Face With Sunglasses',
  'Nerd Face',
  'Face With Monocle',
  'Confused Face',
  'Worried Face',
  'Slightly Frowning Face',
  'Frowning Face',
  'Face With Open Mouth',
  'Hushed Face',
  'Astonished Face',
  'Flushed Face',
  'Pleading Face',
  'Frowning Face With Open Mouth',
  'Anguished Face',
  'Fearful Face',
  'Anxious Face With Sweat',
  'Sad but Relieved Face',
  'Crying Face',
  'Loudly Crying Face',
  'Face Screaming in Fear',
  'Confounded Face',
  'Persevering Face',
  'Disappointed Face',
  'Downcast Face With Sweat',
  'Weary Face',
  'Tired Face',
  'Face With Steam From Nose',
  'Pouting Face',
  'Angry Face',
  'Face With Symbols on Mouth',
  'Smiling Face With Horns',
  'Angry Face With Horns',
  'Skull',
  'Skull and Crossbones',
  'Pile of Poo',
  'Clown Face',
  'Ogre',
  'Goblin',
  'Ghost',
  'Alien',
  'Alien Monster',
  'Robot Face',
  'Grinning Cat Face',
  'Grinning Cat Face With Smiling Eyes',
  'Cat Face With Tears of Joy',
  'Smiling Cat Face With Heart-Eyes',
  'Cat Face With Wry Smile',
  'Kissing Cat Face',
  'Weary Cat Face',
  'Crying Cat Face',
  'Pouting Cat Face',
  'Kiss Mark',
  'Waving Hand',
  'Raised Back of Hand',
  'Hand With Fingers Splayed',
  'Raised Hand',
  'Vulcan Salute',
  'OK Hand',
  'Victory Hand',
  'Crossed Fingers',
  'Love-You Gesture',
  'Sign of the Horns',
  'Call Me Hand',
  'Backhand Index Pointing Left',
  'Backhand Index Pointing Right',
  'Backhand Index Pointing Up',
  'Middle Finger',
  'Backhand Index Pointing Down',
  'Index Pointing Up',
  'Thumbs Up',
  'Thumbs Down',
  'Raised Fist',
  'Oncoming Fist',
  'Left-Facing Fist',
  'Right-Facing Fist',
  'Clapping Hands',
  'Raising Hands',
  'Open Hands',
  'Palms Up Together',
  'Handshake',
  'Folded Hands',
  'Writing Hand',
  'Nail Polish',
  'Selfie',
  'Flexed Biceps',
  'Leg',
  'Foot',
  'Ear',
  'Nose',
  'Brain',
  'Tooth',
  'Bone',
  'Eyes',
  'Eye',
  'Tongue',
  'Mouth',
  'Baby',
  'Child',
  'Boy',
  'Girl',
  'Person',
  'Man',
  'Man: Beard',
  'Man: Blond Hair',
  'Man: Red Hair',
  'Man: Curly Hair',
  'Man: White Hair',
  'Man: Bald',
  'Woman',
  'Woman: Blond Hair',
  'Woman: Red Hair',
  'Woman: Curly Hair',
  'Woman: White Hair',
  'Woman: Bald',
  'Older Person',
  'Old Man',
  'Old Woman',
  'Man Frowning',
  'Woman Frowning',
  'Man Pouting',
  'Woman Pouting',
  'Man Gesturing No',
  'Woman Gesturing No',
  'Man Gesturing OK',
  'Woman Gesturing OK',
  'Man Tipping Hand',
  'Woman Tipping Hand',
  'Man Raising Hand',
  'Woman Raising Hand',
  'Man Bowing',
  'Woman Bowing',
  'Man Facepalming',
  'Woman Facepalming',
  'Man Shrugging',
  'Woman Shrugging',
  'Man Health Worker',
  'Woman Health Worker',
  'Man Student',
  'Woman Student',
  'Man Teacher',
  'Woman Teacher',
  'Man Judge',
  'Woman Judge',
  'Man Farmer',
  'Woman Farmer',
  'Man Cook',
  'Woman Cook',
  'Man Mechanic',
  'Woman Mechanic',
  'Man Factory Worker',
  'Woman Factory Worker',
  'Man Office Worker',
  'Woman Office Worker',
  'Man Scientist',
  'Woman Scientist',
  'Man Technologist',
  'Woman Technologist',
  'Man Singer',
  'Woman Singer',
  'Man Artist',
  'Woman Artist',
  'Man Pilot',
  'Woman Pilot',
  'Man Astronaut',
  'Woman Astronaut',
  'Man Firefighter',
  'Woman Firefighter',
  'Man Police Officer',
  'Woman Police Officer',
  'Man Detective',
  'Woman Detective',
  'Man Guard',
  'Woman Guard',
  'Man Construction Worker',
  'Woman Construction Worker',
  'Prince',
  'Princess',
  'Man Wearing Turban',
  'Woman Wearing Turban',
  'Man With Chinese Cap',
  'Woman With Headscarf',
  'Man in Tuxedo',
  'Bride With Veil',
  'Pregnant Woman',
  'Breast-Feeding',
  'Baby Angel',
  'Santa Claus',
  'Mrs. Claus',
  'Man Superhero',
  'Woman Superhero',
  'Man Supervillain',
  'Woman Supervillain',
  'Man Mage',
  'Woman Mage',
  'Man Fairy',
  'Woman Fairy',
  'Man Vampire',
  'Woman Vampire',
  'Merman',
  'Mermaid',
  'Man Elf',
  'Woman Elf',
  'Man Genie',
  'Woman Genie',
  'Man Zombie',
  'Woman Zombie',
  'Man Getting Massage',
  'Woman Getting Massage',
  'Man Getting Haircut',
  'Woman Getting Haircut',
  'Man Walking',
  'Woman Walking',
  'Man Running',
  'Woman Running',
  'Woman Dancing',
  'Man Dancing',
  'Man in Suit Levitating',
  'Men With Bunny Ears',
  'Women With Bunny Ears',
  'Man in Steamy Room',
  'Woman in Steamy Room',
  'Person in Lotus Position',
  'Women Holding Hands',
  'Woman and Man Holding Hands',
  'Men Holding Hands',
  'Kiss',
  'Kiss: Man, Man',
  'Kiss: Woman, Woman',
  'Couple With Heart',
  'Couple With Heart: Man, Man',
  'Couple With Heart: Woman, Woman',
  'Family',
  'Family: Man, Woman, Boy',
  'Family: Man, Woman, Girl',
  'Family: Man, Woman, Girl, Boy',
  'Family: Man, Woman, Boy, Boy',
  'Family: Man, Woman, Girl, Girl',
  'Family: Man, Man, Boy',
  'Family: Man, Man, Girl',
  'Family: Man, Man, Girl, Boy',
  'Family: Man, Man, Boy, Boy',
  'Family: Man, Man, Girl, Girl',
  'Family: Woman, Woman, Boy',
  'Family: Woman, Woman, Girl',
  'Family: Woman, Woman, Girl, Boy',
  'Family: Woman, Woman, Boy, Boy',
  'Family: Woman, Woman, Girl, Girl',
  'Family: Man, Boy',
  'Family: Man, Boy, Boy',
  'Family: Man, Girl',
  'Family: Man, Girl, Boy',
  'Family: Man, Girl, Girl',
  'Family: Woman, Boy',
  'Family: Woman, Boy, Boy',
  'Family: Woman, Girl',
  'Family: Woman, Girl, Boy',
  'Family: Woman, Girl, Girl',
  'Speaking Head',
  'Bust in Silhouette',
  'Busts in Silhouette',
  'Footprints',
  'Luggage',
  'Closed Umbrella',
  'Umbrella',
  'Thread',
  'Yarn',
  'Glasses',
  'Sunglasses',
  'Goggles',
  'Lab Coat',
  'Necktie',
  'T-Shirt',
  'Jeans',
  'Scarf',
  'Gloves',
  'Coat',
  'Socks',
  'Dress',
  'Kimono',
  'Bikini',
  'Woman’s Clothes',
  'Purse',
  'Handbag',
  'Clutch Bag',
  'Backpack',
  'Man’s Shoe',
  'Running Shoe',
  'Hiking Boot',
  'Flat Shoe',
  'High-Heeled Shoe',
  'Woman’s Sandal',
  'Woman’s Boot',
  'Crown',
  'Woman’s Hat',
  'Top Hat',
  'Graduation Cap',
  'Billed Cap',
  'Rescue Worker’s Helmet',
  'Lipstick',
  'Ring',
  'Briefcase'
], [
  '😀',
  '😃',
  '😄',
  '😁',
  '😆',
  '😅',
  '🤣',
  '😂',
  '🙂',
  '🙃',
  '😉',
  '😊',
  '😇',
  '🥰',
  '😍',
  '🤩',
  '😘',
  '😗',
  '☺',
  '😚',
  '😙',
  '😋',
  '😛',
  '😜',
  '🤪',
  '😝',
  '🤑',
  '🤗',
  '🤭',
  '🤫',
  '🤔',
  '🤐',
  '🤨',
  '😐',
  '😑',
  '😶',
  '😏',
  '😒',
  '🙄',
  '😬',
  '🤥',
  '😌',
  '😔',
  '😪',
  '🤤',
  '😴',
  '😷',
  '🤒',
  '🤕',
  '🤢',
  '🤮',
  '🤧',
  '🥵',
  '🥶',
  '🥴',
  '😵',
  '🤯',
  '🤠',
  '🥳',
  '😎',
  '🤓',
  '🧐',
  '😕',
  '😟',
  '🙁',
  '☹️',
  '🚣',
  '😯',
  '😲',
  '😳',
  '🥺',
  '😦',
  '😧',
  '😨',
  '😰',
  '😥',
  '😢',
  '😭',
  '😱',
  '😖',
  '😣',
  '😞',
  '😓',
  '😩',
  '😫',
  '😤',
  '😡',
  '😠',
  '🤬',
  '😈',
  '👿',
  '💀',
  '☠',
  '💩',
  '🤡',
  '👹',
  '👺',
  '👻',
  '👽',
  '👾',
  '🤖',
  '😺',
  '😸',
  '😹',
  '😻',
  '😼',
  '😽',
  '🙀',
  '😿',
  '😾',
  '💋',
  '👋',
  '🤚',
  '🖐',
  '✋',
  '🖖',
  '👌',
  '✌',
  '🤞',
  '🤟',
  '🤘',
  '🤙',
  '👈',
  '👉',
  '👆',
  '🖕',
  '👇',
  '☝',
  '👍',
  '👎',
  '✊',
  '👊',
  '🤛',
  '🤜',
  '👏',
  '🙌',
  '👐',
  '🤲',
  '🤝',
  '🙏',
  '✍',
  '💅',
  '🤳',
  '💪',
  '🦵',
  '🦶',
  '👂',
  '👃',
  '🧠',
  '🦷',
  '🦴',
  '👀',
  '👁',
  '👅',
  '👄',
  '👶',
  '🧒',
  '👦',
  '👧',
  '🧑',
  '👨',
  '🧔',
  '👱',
  '👨‍🦰',
  '👨‍🦱',
  '👨‍🦳',
  '👨‍🦲',
  '👩',
  '👱',
  '👩‍🦰',
  '👩‍🦱',
  '👩‍🦳',
  '👩‍🦲',
  '🧓',
  '👴',
  '👵',
  '🙍',
  '🙍',
  '🙎',
  '🙎',
  '🙅',
  '🙅',
  '🙆',
  '🙆',
  '💁',
  '💁',
  '🙋',
  '🙋',
  '🙇',
  '🙇',
  '🤦',
  '🤦',
  '🤷',
  '🤷',
  '👨‍⚕️',
  '👩‍⚕️',
  '👨‍🎓',
  '👩‍🎓',
  '👨‍🏫',
  '👩‍🏫',
  '👨‍⚖️',
  '👩‍⚖️',
  '👨‍🌾',
  '👩‍🌾',
  '👨‍🍳',
  '👩‍🍳',
  '👨‍🔧',
  '👩‍🔧',
  '👨‍🏭',
  '👩‍🏭',
  '👨‍💼',
  '👩‍💼',
  '👨‍🔬',
  '👩‍🔬',
  '👨‍💻',
  '👩‍💻',
  '👨‍🎤',
  '👩‍🎤',
  '👨‍🎨',
  '👩‍🎨',
  '👨‍✈️',
  '👩‍✈️',
  '👨‍🚀',
  '👩‍🚀',
  '👨‍🚒',
  '👩‍🚒',
  '👮',
  '👮',
  '🕵️',
  '🕵️',
  '💂',
  '💂',
  '👷',
  '👷',
  '🤴',
  '👸',
  '👳',
  '👳',
  '👲',
  '🧕',
  '🤵',
  '👰',
  '🤰',
  '🤱',
  '👼',
  '🎅',
  '🤶',
  '🦸',
  '🦸',
  '🦹',
  '🦹',
  '🧙',
  '🧙',
  '🧚',
  '🧚',
  '🧛',
  '🧛',
  '🧜',
  '🧜',
  '🧝',
  '🧝',
  '🧞',
  '🧞',
  '🧟',
  '🧟',
  '💆',
  '💆',
  '💇',
  '💇',
  '🚶',
  '🚶',
  '🏃',
  '🏃',
  '💃',
  '🕺',
  '🕴',
  '👯',
  '👯',
  '🧖',
  '🧖',
  '🧘',
  '👭',
  '👫',
  '👬',
  '💏',
  '👨‍❤️‍💋‍👨',
  '👩‍❤️‍💋‍👩',
  '💑',
  '👨‍❤️‍👨',
  '👩‍❤️‍👩',
  '👪',
  '👨‍👩‍👦',
  '👨‍👩‍👧',
  '👨‍👩‍👧‍👦',
  '👨‍👩‍👦‍👦',
  '👨‍👩‍👧‍👧',
  '👨‍👨‍👦',
  '👨‍👨‍👧',
  '👨‍👨‍👧‍👦',
  '👨‍👨‍👦‍👦',
  '👨‍👨‍👧‍👧',
  '👩‍👩‍👦',
  '👩‍👩‍👧',
  '👩‍👩‍👧‍👦',
  '👩‍👩‍👦‍👦',
  '👩‍👩‍👧‍👧',
  '👨‍👦',
  '👨‍👦‍👦',
  '👨‍👧',
  '👨‍👧‍👦',
  '👨‍👧‍👧',
  '👩‍👦',
  '👩‍👦‍👦',
  '👩‍👧',
  '👩‍👧‍👦',
  '👩‍👧‍👧',
  '🗣',
  '👤',
  '👥',
  '👣',
  '🧳',
  '🌂',
  '☂',
  '🧵',
  '🧶',
  '👓',
  '🕶',
  '🥽',
  '🥼',
  '👔',
  '👕',
  '👖',
  '🧣',
  '🧤',
  '🧥',
  '🧦',
  '👗',
  '👘',
  '👙',
  '👚',
  '👛',
  '👜',
  '👝',
  '🎒',
  '👞',
  '👟',
  '🥾',
  '🥿',
  '👠',
  '👡',
  '👢',
  '👑',
  '👒',
  '🎩',
  '🎓',
  '🧢',
  '⛑',
  '💄',
  '💍',
  '💼'
]);

/// Map of all possible emojis along with their names in [Category.ANIMALS]
final Map<String, String> animals = Map.fromIterables([
  'Dog Face',
  'Cat Face',
  'Mouse Face',
  'Hamster Face',
  'Rabbit Face',
  'Fox Face',
  'Bear Face',
  'Panda Face',
  'Tiger Face',
  'Lion Face',
  'Cow Face',
  'Pig Face',
  'Pig Nose',
  'Frog Face',
  'Monkey Face',
  'See-No-Evil Monkey',
  'Hear-No-Evil Monkey',
  'Speak-No-Evil Monkey',
  'Monkey',
  'Collision',
  'Dizzy',
  'Sweat Droplets',
  'Dashing Away',
  'Gorilla',
  'Dog',
  'Poodle',
  'Wolf Face',
  'Raccoon',
  'Cat',
  'Tiger',
  'Leopard',
  'Horse Face',
  'Horse',
  'Unicorn Face',
  'Zebra',
  'Ox',
  'Water Buffalo',
  'Cow',
  'Pig',
  'Boar',
  'Ram',
  'Ewe',
  'Goat',
  'Camel',
  'Two-Hump Camel',
  'Llama',
  'Giraffe',
  'Elephant',
  'Rhinoceros',
  'Hippopotamus',
  'Mouse',
  'Rat',
  'Rabbit',
  'Chipmunk',
  'Hedgehog',
  'Bat',
  'Koala',
  'Kangaroo',
  'Badger',
  'Paw Prints',
  'Turkey',
  'Chicken',
  'Rooster',
  'Hatching Chick',
  'Baby Chick',
  'Front-Facing Baby Chick',
  'Bird',
  'Penguin',
  'Dove',
  'Eagle',
  'Duck',
  'Swan',
  'Owl',
  'Peacock',
  'Parrot',
  'Crocodile',
  'Turtle',
  'Lizard',
  'Snake',
  'Dragon Face',
  'Dragon',
  'Sauropod',
  'T-Rex',
  'Spouting Whale',
  'Whale',
  'Dolphin',
  'Fish',
  'Tropical Fish',
  'Blowfish',
  'Shark',
  'Octopus',
  'Spiral Shell',
  'Snail',
  'Butterfly',
  'Bug',
  'Ant',
  'Honeybee',
  'Lady Beetle',
  'Cricket',
  'Spider',
  'Spider Web',
  'Scorpion',
  'Mosquito',
  'Microbe',
  'Bouquet',
  'Cherry Blossom',
  'White Flower',
  'Rosette',
  'Rose',
  'Wilted Flower',
  'Hibiscus',
  'Sunflower',
  'Blossom',
  'Tulip',
  'Seedling',
  'Evergreen Tree',
  'Deciduous Tree',
  'Palm Tree',
  'Cactus',
  'Sheaf of Rice',
  'Herb',
  'Shamrock',
  'Four Leaf Clover',
  'Maple Leaf',
  'Fallen Leaf',
  'Leaf Fluttering in Wind',
  'Mushroom',
  'Chestnut',
  'Crab',
  'Lobster',
  'Shrimp',
  'Squid',
  'Globe Showing Europe-Africa',
  'Globe Showing Americas',
  'Globe Showing Asia-Australia',
  'Globe With Meridians',
  'New Moon',
  'Waxing Crescent Moon',
  'First Quarter Moon',
  'Waxing Gibbous Moon',
  'Full Moon',
  'Waning Gibbous Moon',
  'Last Quarter Moon',
  'Waning Crescent Moon',
  'Crescent Moon',
  'New Moon Face',
  'First Quarter Moon Face',
  'Last Quarter Moon Face',
  'Sun',
  'Full Moon Face',
  'Sun With Face',
  'Star',
  'Glowing Star',
  'Shooting Star',
  'Cloud',
  'Sun Behind Cloud',
  'Cloud With Lightning and Rain',
  'Sun Behind Small Cloud',
  'Sun Behind Large Cloud',
  'Sun Behind Rain Cloud',
  'Cloud With Rain',
  'Cloud With Snow',
  'Cloud With Lightning',
  'Tornado',
  'Fog',
  'Wind Face',
  'Rainbow',
  'Umbrella',
  'Umbrella With Rain Drops',
  'High Voltage',
  'Snowflake',
  'Snowman',
  'Snowman Without Snow',
  'Comet',
  'Fire',
  'Droplet',
  'Water Wave',
  'Christmas Tree',
  'Sparkles',
  'Tanabata Tree',
  'Pine Decoration'
], [
  '🐶',
  '🐱',
  '🐭',
  '🐹',
  '🐰',
  '🦊',
  '🐻',
  '🐼',
  '🐨',
  '🐯',
  '🦁',
  '🐮',
  '🐷',
  '🐽',
  '🐸',
  '🐵',
  '🙈',
  '🙉',
  '🙊',
  '🐒',
  '💥',
  '💫',
  '💦',
  '💨',
  '🦍',
  '🐕',
  '🐩',
  '🐺',
  '🦝',
  '🐈',
  '🐅',
  '🐆',
  '🐴',
  '🐎',
  '🦄',
  '🦓',
  '🐂',
  '🐃',
  '🐄',
  '🐖',
  '🐗',
  '🐏',
  '🐑',
  '🐐',
  '🐪',
  '🐫',
  '🦙',
  '🦒',
  '🐘',
  '🦏',
  '🦛',
  '🐁',
  '🐀',
  '🐇',
  '🐿',
  '🦔',
  '🦇',
  '🦘',
  '🦡',
  '🐾',
  '🦃',
  '🐔',
  '🐓',
  '🐣',
  '🐤',
  '🐥',
  '🐦',
  '🐧',
  '🕊',
  '🦅',
  '🦆',
  '🦢',
  '🦉',
  '🦚',
  '🦜',
  '🐊',
  '🐢',
  '🦎',
  '🐍',
  '🐲',
  '🐉',
  '🦕',
  '🦖',
  '🐳',
  '🐋',
  '🐬',
  '🐟',
  '🐠',
  '🐡',
  '🦈',
  '🐙',
  '🐚',
  '🐌',
  '🦋',
  '🐛',
  '🐜',
  '🐝',
  '🐞',
  '🦗',
  '🕷',
  '🕸',
  '🦂',
  '🦟',
  '🦠',
  '💐',
  '🌸',
  '💮',
  '🏵',
  '🌹',
  '🥀',
  '🌺',
  '🌻',
  '🌼',
  '🌷',
  '🌱',
  '🌲',
  '🌳',
  '🌴',
  '🌵',
  '🌾',
  '🌿',
  '☘',
  '🍀',
  '🍁',
  '🍂',
  '🍃',
  '🍄',
  '🌰',
  '🦀',
  '🦞',
  '🦐',
  '🦑',
  '🌍',
  '🌎',
  '🌏',
  '🌐',
  '🌑',
  '🌒',
  '🌓',
  '🌔',
  '🌕',
  '🌖',
  '🌗',
  '🌘',
  '🌙',
  '🌚',
  '🌛',
  '🌜',
  '☀',
  '🌝',
  '🌞',
  '⭐',
  '🌟',
  '🌠',
  '☁',
  '⛅',
  '⛈',
  '🌤',
  '🌥',
  '🌦',
  '🌧',
  '🌨',
  '🌩',
  '🌪',
  '🌫',
  '🌬',
  '🌈',
  '☂',
  '☔',
  '⚡',
  '❄',
  '☃',
  '⛄',
  '☄',
  '🔥',
  '💧',
  '🌊',
  '🎄',
  '✨',
  '🎋',
  '🎍'
]);

/// Map of all possible emojis along with their names in [Category.FOODS]
final Map<String, String> foods = Map.fromIterables([
  'Grapes',
  'Melon',
  'Watermelon',
  'Tangerine',
  'Lemon',
  'Banana',
  'Pineapple',
  'Mango',
  'Red Apple',
  'Green Apple',
  'Pear',
  'Peach',
  'Cherries',
  'Strawberry',
  'Kiwi Fruit',
  'Tomato',
  'Coconut',
  'Avocado',
  'Eggplant',
  'Potato',
  'Carrot',
  'Ear of Corn',
  'Hot Pepper',
  'Cucumber',
  'Leafy Green',
  'Broccoli',
  'Mushroom',
  'Peanuts',
  'Chestnut',
  'Bread',
  'Croissant',
  'Baguette Bread',
  'Pretzel',
  'Bagel',
  'Pancakes',
  'Cheese Wedge',
  'Meat on Bone',
  'Poultry Leg',
  'Cut of Meat',
  'Bacon',
  'Hamburger',
  'French Fries',
  'Pizza',
  'Hot Dog',
  'Sandwich',
  'Taco',
  'Burrito',
  'Stuffed Flatbread',
  'Cooking',
  'Shallow Pan of Food',
  'Pot of Food',
  'Bowl With Spoon',
  'Green Salad',
  'Popcorn',
  'Salt',
  'Canned Food',
  'Bento Box',
  'Rice Cracker',
  'Rice Ball',
  'Cooked Rice',
  'Curry Rice',
  'Steaming Bowl',
  'Spaghetti',
  'Roasted Sweet Potato',
  'Oden',
  'Sushi',
  'Fried Shrimp',
  'Fish Cake With Swirl',
  'Moon Cake',
  'Dango',
  'Dumpling',
  'Fortune Cookie',
  'Takeout Box',
  'Soft Ice Cream',
  'Shaved Ice',
  'Ice Cream',
  'Doughnut',
  'Cookie',
  'Birthday Cake',
  'Shortcake',
  'Cupcake',
  'Pie',
  'Chocolate Bar',
  'Candy',
  'Lollipop',
  'Custard',
  'Honey Pot',
  'Baby Bottle',
  'Glass of Milk',
  'Hot Beverage',
  'Teacup Without Handle',
  'Sake',
  'Bottle With Popping Cork',
  'Wine Glass',
  'Cocktail Glass',
  'Tropical Drink',
  'Beer Mug',
  'Clinking Beer Mugs',
  'Clinking Glasses',
  'Tumbler Glass',
  'Cup With Straw',
  'Chopsticks',
  'Fork and Knife With Plate',
  'Fork and Knife',
  'Spoon'
], [
  '🍇',
  '🍈',
  '🍉',
  '🍊',
  '🍋',
  '🍌',
  '🍍',
  '🥭',
  '🍎',
  '🍏',
  '🍐',
  '🍑',
  '🍒',
  '🍓',
  '🥝',
  '🍅',
  '🥥',
  '🥑',
  '🍆',
  '🥔',
  '🥕',
  '🌽',
  '🌶',
  '🥒',
  '🥬',
  '🥦',
  '🍄',
  '🥜',
  '🌰',
  '🍞',
  '🥐',
  '🥖',
  '🥨',
  '🥯',
  '🥞',
  '🧀',
  '🍖',
  '🍗',
  '🥩',
  '🥓',
  '🍔',
  '🍟',
  '🍕',
  '🌭',
  '🥪',
  '🌮',
  '🌯',
  '🥙',
  '🍳',
  '🥘',
  '🍲',
  '🥣',
  '🥗',
  '🍿',
  '🧂',
  '🥫',
  '🍱',
  '🍘',
  '🍙',
  '🍚',
  '🍛',
  '🍜',
  '🍝',
  '🍠',
  '🍢',
  '🍣',
  '🍤',
  '🍥',
  '🥮',
  '🍡',
  '🥟',
  '🥠',
  '🥡',
  '🍦',
  '🍧',
  '🍨',
  '🍩',
  '🍪',
  '🎂',
  '🍰',
  '🧁',
  '🥧',
  '🍫',
  '🍬',
  '🍭',
  '🍮',
  '🍯',
  '🍼',
  '🥛',
  '☕',
  '🍵',
  '🍶',
  '🍾',
  '🍷',
  '🍸',
  '🍹',
  '🍺',
  '🍻',
  '🥂',
  '🥃',
  '🥤',
  '🥢',
  '🍽',
  '🍴',
  '🥄'
]);

/// Map of all possible emojis along with their names in [Category.TRAVEL]
final Map<String, String> travel = Map.fromIterables([
  'Person Rowing Boat',
  'Map of Japan',
  'Snow-Capped Mountain',
  'Mountain',
  'Volcano',
  'Mount Fuji',
  'Camping',
  'Beach With Umbrella',
  'Desert',
  'Desert Island',
  'National Park',
  'Stadium',
  'Classical Building',
  'Building Construction',
  'Houses',
  'Derelict House',
  'House',
  'House With Garden',
  'Office Building',
  'Japanese Post Office',
  'Post Office',
  'Hospital',
  'Bank',
  'Hotel',
  'Love Hotel',
  'Convenience Store',
  'School',
  'Department Store',
  'Factory',
  'Japanese Castle',
  'Castle',
  'Wedding',
  'Tokyo Tower',
  'Statue of Liberty',
  'Church',
  'Mosque',
  'Synagogue',
  'Shinto Shrine',
  'Kaaba',
  'Fountain',
  'Tent',
  'Foggy',
  'Night With Stars',
  'Cityscape',
  'Sunrise Over Mountains',
  'Sunrise',
  'Cityscape at Dusk',
  'Sunset',
  'Bridge at Night',
  'Carousel Horse',
  'Ferris Wheel',
  'Roller Coaster',
  'Locomotive',
  'Railway Car',
  'High-Speed Train',
  'Bullet Train',
  'Train',
  'Metro',
  'Light Rail',
  'Station',
  'Tram',
  'Monorail',
  'Mountain Railway',
  'Tram Car',
  'Bus',
  'Oncoming Bus',
  'Trolleybus',
  'Minibus',
  'Ambulance',
  'Fire Engine',
  'Police Car',
  'Oncoming Police Car',
  'Taxi',
  'Oncoming Taxi',
  'Automobile',
  'Oncoming Automobile',
  'Delivery Truck',
  'Articulated Lorry',
  'Tractor',
  'Racing Car',
  'Motorcycle',
  'Motor Scooter',
  'Bicycle',
  'Kick Scooter',
  'Bus Stop',
  'Railway Track',
  'Fuel Pump',
  'Police Car Light',
  'Horizontal Traffic Light',
  'Vertical Traffic Light',
  'Construction',
  'Anchor',
  'Sailboat',
  'Speedboat',
  'Passenger Ship',
  'Ferry',
  'Motor Boat',
  'Ship',
  'Airplane',
  'Small Airplane',
  'Airplane Departure',
  'Airplane Arrival',
  'Seat',
  'Helicopter',
  'Suspension Railway',
  'Mountain Cableway',
  'Aerial Tramway',
  'Satellite',
  'Rocket',
  'Flying Saucer',
  'Shooting Star',
  'Milky Way',
  'Umbrella on Ground',
  'Fireworks',
  'Sparkler',
  'Moon Viewing Ceremony',
  'Yen Banknote',
  'Dollar Banknote',
  'Euro Banknote',
  'Pound Banknote',
  'Moai',
  'Passport Control',
  'Customs',
  'Baggage Claim',
  'Left Luggage'
], [
  '🚣',
  '🗾',
  '🏔',
  '⛰',
  '🌋',
  '🗻',
  '🏕',
  '🏖',
  '🏜',
  '🏝',
  '🏞',
  '🏟',
  '🏛',
  '🏗',
  '🏘',
  '🏚',
  '🏠',
  '🏡',
  '🏢',
  '🏣',
  '🏤',
  '🏥',
  '🏦',
  '🏨',
  '🏩',
  '🏪',
  '🏫',
  '🏬',
  '🏭',
  '🏯',
  '🏰',
  '💒',
  '🗼',
  '🗽',
  '⛪',
  '🕌',
  '🕍',
  '⛩',
  '🕋',
  '⛲',
  '⛺',
  '🌁',
  '🌃',
  '🏙',
  '🌄',
  '🌅',
  '🌆',
  '🌇',
  '🌉',
  '🎠',
  '🎡',
  '🎢',
  '🚂',
  '🚃',
  '🚄',
  '🚅',
  '🚆',
  '🚇',
  '🚈',
  '🚉',
  '🚊',
  '🚝',
  '🚞',
  '🚋',
  '🚌',
  '🚍',
  '🚎',
  '🚐',
  '🚑',
  '🚒',
  '🚓',
  '🚔',
  '🚕',
  '🚖',
  '🚗',
  '🚘',
  '🚚',
  '🚛',
  '🚜',
  '🏎',
  '🏍',
  '🛵',
  '🚲',
  '🛴',
  '🚏',
  '🛤',
  '⛽',
  '🚨',
  '🚥',
  '🚦',
  '🚧',
  '⚓',
  '⛵',
  '🚤',
  '🛳',
  '⛴',
  '🛥',
  '🚢',
  '✈',
  '🛩',
  '🛫',
  '🛬',
  '💺',
  '🚁',
  '🚟',
  '🚠',
  '🚡',
  '🛰',
  '🚀',
  '🛸',
  '🌠',
  '🌌',
  '⛱',
  '🎆',
  '🎇',
  '🎑',
  '💴',
  '💵',
  '💶',
  '💷',
  '🗿',
  '🛂',
  '🛃',
  '🛄',
  '🛅'
]);

/// Map of all possible emojis along with their names in [Category.ACTIVITIES]
final Map<String, String> activities = Map.fromIterables([
  'Man in Suit Levitating',
  'Man Climbing',
  'Woman Climbing',
  'Horse Racing',
  'Skier',
  'Snowboarder',
  'Man Golfing',
  'Woman Golfing',
  'Man Surfing',
  'Woman Surfing',
  'Man Rowing Boat',
  'Woman Rowing Boat',
  'Man Swimming',
  'Woman Swimming',
  'Man Bouncing Ball',
  'Woman Bouncing Ball',
  'Man Lifting Weights',
  'Woman Lifting Weights',
  'Man Biking',
  'Woman Biking',
  'Man Mountain Biking',
  'Woman Mountain Biking',
  'Man Cartwheeling',
  'Woman Cartwheeling',
  'Men Wrestling',
  'Women Wrestling',
  'Man Playing Water Polo',
  'Woman Playing Water Polo',
  'Man Playing Handball',
  'Woman Playing Handball',
  'Man Juggling',
  'Woman Juggling',
  'Man in Lotus Position',
  'Woman in Lotus Position',
  'Circus Tent',
  'Skateboard',
  'Reminder Ribbon',
  'Admission Tickets',
  'Ticket',
  'Military Medal',
  'Trophy',
  'Sports Medal',
  '1st Place Medal',
  '2nd Place Medal',
  '3rd Place Medal',
  'Soccer Ball',
  'Baseball',
  'Softball',
  'Basketball',
  'Volleyball',
  'American Football',
  'Rugby Football',
  'Tennis',
  'Flying Disc',
  'Bowling',
  'Cricket Game',
  'Field Hockey',
  'Ice Hockey',
  'Lacrosse',
  'Ping Pong',
  'Badminton',
  'Boxing Glove',
  'Martial Arts Uniform',
  'Flag in Hole',
  'Ice Skate',
  'Fishing Pole',
  'Running Shirt',
  'Skis',
  'Sled',
  'Curling Stone',
  'Direct Hit',
  'Pool 8 Ball',
  'Video Game',
  'Slot Machine',
  'Game Die',
  'Jigsaw',
  'Chess Pawn',
  'Performing Arts',
  'Artist Palette',
  'Thread',
  'Yarn',
  'Musical Score',
  'Microphone',
  'Headphone',
  'Saxophone',
  'Guitar',
  'Musical Keyboard',
  'Trumpet',
  'Violin',
  'Drum',
  'Clapper Board',
  'Bow and Arrow'
], [
  '🕴',
  '🧗',
  '🧗',
  '🏇',
  '⛷',
  '🏂',
  '🏌️',
  '🏌️',
  '🏄',
  '🏄',
  '🚣',
  '🚣',
  '🏊',
  '🏊',
  '⛹️',
  '⛹️',
  '🏋️',
  '🏋️',
  '🚴',
  '🚴',
  '🚵',
  '🚵',
  '🤸',
  '🤸',
  '🤼',
  '🤼',
  '🤽',
  '🤽',
  '🤾',
  '🤾',
  '🤹',
  '🤹',
  '🧘🏻‍♂️',
  '🧘🏻‍♀️',
  '🎪',
  '🛹',
  '🎗',
  '🎟',
  '🎫',
  '🎖',
  '🏆',
  '🏅',
  '🥇',
  '🥈',
  '🥉',
  '⚽',
  '⚾',
  '🥎',
  '🏀',
  '🏐',
  '🏈',
  '🏉',
  '🎾',
  '🥏',
  '🎳',
  '🏏',
  '🏑',
  '🏒',
  '🥍',
  '🏓',
  '🏸',
  '🥊',
  '🥋',
  '⛳',
  '⛸',
  '🎣',
  '🎽',
  '🎿',
  '🛷',
  '🥌',
  '🎯',
  '🎱',
  '🎮',
  '🎰',
  '🎲',
  '🧩',
  '♟',
  '🎭',
  '🎨',
  '🧵',
  '🧶',
  '🎼',
  '🎤',
  '🎧',
  '🎷',
  '🎸',
  '🎹',
  '🎺',
  '🎻',
  '🥁',
  '🎬',
  '🏹'
]);

/// Map of all possible emojis along with their names in [Category.OBJECTS]
final Map<String, String> objects = Map.fromIterables([
  'Love Letter',
  'Hole',
  'Bomb',
  'Person Taking Bath',
  'Person in Bed',
  'Kitchen Knife',
  'Amphora',
  'World Map',
  'Compass',
  'Brick',
  'Barber Pole',
  'Oil Drum',
  'Bellhop Bell',
  'Luggage',
  'Hourglass Done',
  'Hourglass Not Done',
  'Watch',
  'Alarm Clock',
  'Stopwatch',
  'Timer Clock',
  'Mantelpiece Clock',
  'Thermometer',
  'Umbrella on Ground',
  'Firecracker',
  'Balloon',
  'Party Popper',
  'Confetti Ball',
  'Japanese Dolls',
  'Carp Streamer',
  'Wind Chime',
  'Red Envelope',
  'Ribbon',
  'Wrapped Gift',
  'Crystal Ball',
  'Nazar Amulet',
  'Joystick',
  'Teddy Bear',
  'Framed Picture',
  'Thread',
  'Yarn',
  'Shopping Bags',
  'Prayer Beads',
  'Gem Stone',
  'Postal Horn',
  'Studio Microphone',
  'Level Slider',
  'Control Knobs',
  'Radio',
  'Mobile Phone',
  'Mobile Phone With Arrow',
  'Telephone',
  'Telephone Receiver',
  'Pager',
  'Fax Machine',
  'Battery',
  'Electric Plug',
  'Laptop Computer',
  'Desktop Computer',
  'Printer',
  'Keyboard',
  'Computer Mouse',
  'Trackball',
  'Computer Disk',
  'Floppy Disk',
  'Optical Disk',
  'DVD',
  'Abacus',
  'Movie Camera',
  'Film Frames',
  'Film Projector',
  'Television',
  'Camera',
  'Camera With Flash',
  'Video Camera',
  'Videocassette',
  'Magnifying Glass Tilted Left',
  'Magnifying Glass Tilted Right',
  'Candle',
  'Light Bulb',
  'Flashlight',
  'Red Paper Lantern',
  'Notebook With Decorative Cover',
  'Closed Book',
  'Open Book',
  'Green Book',
  'Blue Book',
  'Orange Book',
  'Books',
  'Notebook',
  'Page With Curl',
  'Scroll',
  'Page Facing Up',
  'Newspaper',
  'Rolled-Up Newspaper',
  'Bookmark Tabs',
  'Bookmark',
  'Label',
  'Money Bag',
  'Yen Banknote',
  'Dollar Banknote',
  'Euro Banknote',
  'Pound Banknote',
  'Money With Wings',
  'Credit Card',
  'Receipt',
  'Envelope',
  'E-Mail',
  'Incoming Envelope',
  'Envelope With Arrow',
  'Outbox Tray',
  'Inbox Tray',
  'Package',
  'Closed Mailbox With Raised Flag',
  'Closed Mailbox With Lowered Flag',
  'Open Mailbox With Raised Flag',
  'Open Mailbox With Lowered Flag',
  'Postbox',
  'Ballot Box With Ballot',
  'Pencil',
  'Black Nib',
  'Fountain Pen',
  'Pen',
  'Paintbrush',
  'Crayon',
  'Memo',
  'File Folder',
  'Open File Folder',
  'Card Index Dividers',
  'Calendar',
  'Tear-Off Calendar',
  'Spiral Notepad',
  'Spiral Calendar',
  'Card Index',
  'Chart Increasing',
  'Chart Decreasing',
  'Bar Chart',
  'Clipboard',
  'Pushpin',
  'Round Pushpin',
  'Paperclip',
  'Linked Paperclips',
  'Straight Ruler',
  'Triangular Ruler',
  'Scissors',
  'Card File Box',
  'File Cabinet',
  'Wastebasket',
  'Locked',
  'Unlocked',
  'Locked With Pen',
  'Locked With Key',
  'Key',
  'Old Key',
  'Hammer',
  'Pick',
  'Hammer and Pick',
  'Hammer and Wrench',
  'Dagger',
  'Crossed Swords',
  'Pistol',
  'Shield',
  'Wrench',
  'Nut and Bolt',
  'Gear',
  'Clamp',
  'Balance Scale',
  'Link',
  'Chains',
  'Toolbox',
  'Magnet',
  'Alembic',
  'Test Tube',
  'Petri Dish',
  'DNA',
  'Microscope',
  'Telescope',
  'Satellite Antenna',
  'Syringe',
  'Pill',
  'Door',
  'Bed',
  'Couch and Lamp',
  'Toilet',
  'Shower',
  'Bathtub',
  'Lotion Bottle',
  'Safety Pin',
  'Broom',
  'Basket',
  'Roll of Paper',
  'Soap',
  'Sponge',
  'Fire Extinguisher',
  'Cigarette',
  'Coffin',
  'Funeral Urn',
  'Moai',
  'Potable Water'
], [
  '💌',
  '🕳',
  '💣',
  '🛀',
  '🛌',
  '🔪',
  '🏺',
  '🗺',
  '🧭',
  '🧱',
  '💈',
  '🛢',
  '🛎',
  '🧳',
  '⌛',
  '⏳',
  '⌚',
  '⏰',
  '⏱',
  '⏲',
  '🕰',
  '🌡',
  '⛱',
  '🧨',
  '🎈',
  '🎉',
  '🎊',
  '🎎',
  '🎏',
  '🎐',
  '🧧',
  '🎀',
  '🎁',
  '🔮',
  '🧿',
  '🕹',
  '🧸',
  '🖼',
  '🧵',
  '🧶',
  '🛍',
  '📿',
  '💎',
  '📯',
  '🎙',
  '🎚',
  '🎛',
  '📻',
  '📱',
  '📲',
  '☎',
  '📞',
  '📟',
  '📠',
  '🔋',
  '🔌',
  '💻',
  '🖥',
  '🖨',
  '⌨',
  '🖱',
  '🖲',
  '💽',
  '💾',
  '💿',
  '📀',
  '🧮',
  '🎥',
  '🎞',
  '📽',
  '📺',
  '📷',
  '📸',
  '📹',
  '📼',
  '🔍',
  '🔎',
  '🕯',
  '💡',
  '🔦',
  '🏮',
  '📔',
  '📕',
  '📖',
  '📗',
  '📘',
  '📙',
  '📚',
  '📓',
  '📃',
  '📜',
  '📄',
  '📰',
  '🗞',
  '📑',
  '🔖',
  '🏷',
  '💰',
  '💴',
  '💵',
  '💶',
  '💷',
  '💸',
  '💳',
  '🧾',
  '✉',
  '📧',
  '📨',
  '📩',
  '📤',
  '📥',
  '📦',
  '📫',
  '📪',
  '📬',
  '📭',
  '📮',
  '🗳',
  '✏',
  '✒',
  '🖋',
  '🖊',
  '🖌',
  '🖍',
  '📝',
  '📁',
  '📂',
  '🗂',
  '📅',
  '📆',
  '🗒',
  '🗓',
  '📇',
  '📈',
  '📉',
  '📊',
  '📋',
  '📌',
  '📍',
  '📎',
  '🖇',
  '📏',
  '📐',
  '✂',
  '🗃',
  '🗄',
  '🗑',
  '🔒',
  '🔓',
  '🔏',
  '🔐',
  '🔑',
  '🗝',
  '🔨',
  '⛏',
  '⚒',
  '🛠',
  '🗡',
  '⚔',
  '🔫',
  '🛡',
  '🔧',
  '🔩',
  '⚙',
  '🗜',
  '⚖',
  '🔗',
  '⛓',
  '🧰',
  '🧲',
  '⚗',
  '🧪',
  '🧫',
  '🧬',
  '🔬',
  '🔭',
  '📡',
  '💉',
  '💊',
  '🚪',
  '🛏',
  '🛋',
  '🚽',
  '🚿',
  '🛁',
  '🧴',
  '🧷',
  '🧹',
  '🧺',
  '🧻',
  '🧼',
  '🧽',
  '🧯',
  '🚬',
  '⚰',
  '⚱',
  '🗿',
  '🚰'
]);

/// Map of all possible emojis along with their names in [Category.SYMBOLS]
final Map<String, String> symbols = Map.fromIterables([
  'Heart With Arrow',
  'Heart With Ribbon',
  'Sparkling Heart',
  'Growing Heart',
  'Beating Heart',
  'Revolving Hearts',
  'Two Hearts',
  'Heart Decoration',
  'Heavy Heart Exclamation',
  'Broken Heart',
  'Red Heart',
  'Orange Heart',
  'Yellow Heart',
  'Green Heart',
  'Blue Heart',
  'Purple Heart',
  'Black Heart',
  'Hundred Points',
  'Anger Symbol',
  'Speech Balloon',
  'Eye in Speech Bubble',
  'Right Anger Bubble',
  'Thought Balloon',
  'Zzz',
  'White Flower',
  'Hot Springs',
  'Barber Pole',
  'Stop Sign',
  'Twelve O’Clock',
  'Twelve-Thirty',
  'One O’Clock',
  'One-Thirty',
  'Two O’Clock',
  'Two-Thirty',
  'Three O’Clock',
  'Three-Thirty',
  'Four O’Clock',
  'Four-Thirty',
  'Five O’Clock',
  'Five-Thirty',
  'Six O’Clock',
  'Six-Thirty',
  'Seven O’Clock',
  'Seven-Thirty',
  'Eight O’Clock',
  'Eight-Thirty',
  'Nine O’Clock',
  'Nine-Thirty',
  'Ten O’Clock',
  'Ten-Thirty',
  'Eleven O’Clock',
  'Eleven-Thirty',
  'Cyclone',
  'Spade Suit',
  'Heart Suit',
  'Diamond Suit',
  'Club Suit',
  'Joker',
  'Mahjong Red Dragon',
  'Flower Playing Cards',
  'Muted Speaker',
  'Speaker Low Volume',
  'Speaker Medium Volume',
  'Speaker High Volume',
  'Loudspeaker',
  'Megaphone',
  'Postal Horn',
  'Bell',
  'Bell With Slash',
  'Musical Note',
  'Musical Notes',
  'ATM Sign',
  'Litter in Bin Sign',
  'Potable Water',
  'Wheelchair Symbol',
  'Men’s Room',
  'Women’s Room',
  'Restroom',
  'Baby Symbol',
  'Water Closet',
  'Warning',
  'Children Crossing',
  'No Entry',
  'Prohibited',
  'No Bicycles',
  'No Smoking',
  'No Littering',
  'Non-Potable Water',
  'No Pedestrians',
  'No One Under Eighteen',
  'Radioactive',
  'Biohazard',
  'Up Arrow',
  'Up-Right Arrow',
  'Right Arrow',
  'Down-Right Arrow',
  'Down Arrow',
  'Down-Left Arrow',
  'Left Arrow',
  'Up-Left Arrow',
  'Up-Down Arrow',
  'Left-Right Arrow',
  'Right Arrow Curving Left',
  'Left Arrow Curving Right',
  'Right Arrow Curving Up',
  'Right Arrow Curving Down',
  'Clockwise Vertical Arrows',
  'Counterclockwise Arrows Button',
  'Back Arrow',
  'End Arrow',
  'On! Arrow',
  'Soon Arrow',
  'Top Arrow',
  'Place of Worship',
  'Atom Symbol',
  'Om',
  'Star of David',
  'Wheel of Dharma',
  'Yin Yang',
  'Latin Cross',
  'Orthodox Cross',
  'Star and Crescent',
  'Peace Symbol',
  'Menorah',
  'Dotted Six-Pointed Star',
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces',
  'Ophiuchus',
  'Shuffle Tracks Button',
  'Repeat Button',
  'Repeat Single Button',
  'Play Button',
  'Fast-Forward Button',
  'Reverse Button',
  'Fast Reverse Button',
  'Upwards Button',
  'Fast Up Button',
  'Downwards Button',
  'Fast Down Button',
  'Stop Button',
  'Eject Button',
  'Cinema',
  'Dim Button',
  'Bright Button',
  'Antenna Bars',
  'Vibration Mode',
  'Mobile Phone Off',
  'Infinity',
  'Recycling Symbol',
  'Trident Emblem',
  'Name Badge',
  'Japanese Symbol for Beginner',
  'Heavy Large Circle',
  'White Heavy Check Mark',
  'Ballot Box With Check',
  'Heavy Check Mark',
  'Heavy Multiplication X',
  'Cross Mark',
  'Cross Mark Button',
  'Heavy Plus Sign',
  'Heavy Minus Sign',
  'Heavy Division Sign',
  'Curly Loop',
  'Double Curly Loop',
  'Part Alternation Mark',
  'Eight-Spoked Asterisk',
  'Eight-Pointed Star',
  'Sparkle',
  'Double Exclamation Mark',
  'Exclamation Question Mark',
  'Question Mark',
  'White Question Mark',
  'White Exclamation Mark',
  'Exclamation Mark',
  'Copyright',
  'Registered',
  'Trade Mark',
  'Keycap Number Sign',
  'Keycap Digit Zero',
  'Keycap Digit One',
  'Keycap Digit Two',
  'Keycap Digit Three',
  'Keycap Digit Four',
  'Keycap Digit Five',
  'Keycap Digit Six',
  'Keycap Digit Seven',
  'Keycap Digit Eight',
  'Keycap Digit Nine',
  'Keycap: 10',
  'Input Latin Uppercase',
  'Input Latin Lowercase',
  'Input Numbers',
  'Input Symbols',
  'Input Latin Letters',
  'A Button (Blood Type)',
  'AB Button (Blood Type)',
  'B Button (Blood Type)',
  'CL Button',
  'Cool Button',
  'Free Button',
  'Information',
  'ID Button',
  'Circled M',
  'New Button',
  'NG Button',
  'O Button (Blood Type)',
  'OK Button',
  'P Button',
  'SOS Button',
  'Up! Button',
  'Vs Button',
  'Japanese “Here” Button',
  'Japanese “Service Charge” Button',
  'Japanese “Monthly Amount” Button',
  'Japanese “Not Free of Charge” Button',
  'Japanese “Reserved” Button',
  'Japanese “Bargain” Button',
  'Japanese “Discount” Button',
  'Japanese “Free of Charge” Button',
  'Japanese “Prohibited” Button',
  'Japanese “Acceptable” Button',
  'Japanese “Application” Button',
  'Japanese “Passing Grade” Button',
  'Japanese “Vacancy” Button',
  'Japanese “Congratulations” Button',
  'Japanese “Secret” Button',
  'Japanese “Open for Business” Button',
  'Japanese “No Vacancy” Button',
  'Red Circle',
  'Blue Circle',
  'Black Circle',
  'White Circle',
  'Black Large Square',
  'White Large Square',
  'Black Medium Square',
  'White Medium Square',
  'Black Medium-Small Square',
  'White Medium-Small Square',
  'Black Small Square',
  'White Small Square',
  'Large Orange Diamond',
  'Large Blue Diamond',
  'Small Orange Diamond',
  'Small Blue Diamond',
  'Red Triangle Pointed Up',
  'Red Triangle Pointed Down',
  'Diamond With a Dot',
  'White Square Button',
  'Black Square Button'
], [
  '💘',
  '💝',
  '💖',
  '💗',
  '💓',
  '💞',
  '💕',
  '💟',
  '❣',
  '💔',
  '❤',
  '🧡',
  '💛',
  '💚',
  '💙',
  '💜',
  '🖤',
  '💯',
  '💢',
  '💬',
  '👁️‍🗨️',
  '🗯',
  '💭',
  '💤',
  '💮',
  '♨',
  '💈',
  '🛑',
  '🕛',
  '🕧',
  '🕐',
  '🕜',
  '🕑',
  '🕝',
  '🕒',
  '🕞',
  '🕓',
  '🕟',
  '🕔',
  '🕠',
  '🕕',
  '🕡',
  '🕖',
  '🕢',
  '🕗',
  '🕣',
  '🕘',
  '🕤',
  '🕙',
  '🕥',
  '🕚',
  '🕦',
  '🌀',
  '♠',
  '♥',
  '♦',
  '♣',
  '🃏',
  '🀄',
  '🎴',
  '🔇',
  '🔈',
  '🔉',
  '🔊',
  '📢',
  '📣',
  '📯',
  '🔔',
  '🔕',
  '🎵',
  '🎶',
  '🏧',
  '🚮',
  '🚰',
  '♿',
  '🚹',
  '🚺',
  '🚻',
  '🚼',
  '🚾',
  '⚠',
  '🚸',
  '⛔',
  '🚫',
  '🚳',
  '🚭',
  '🚯',
  '🚱',
  '🚷',
  '🔞',
  '☢',
  '☣',
  '⬆',
  '↗',
  '➡',
  '↘',
  '⬇',
  '↙',
  '⬅',
  '↖',
  '↕',
  '↔',
  '↩',
  '↪',
  '⤴',
  '⤵',
  '🔃',
  '🔄',
  '🔙',
  '🔚',
  '🔛',
  '🔜',
  '🔝',
  '🛐',
  '⚛',
  '🕉',
  '✡',
  '☸',
  '☯',
  '✝',
  '☦',
  '☪',
  '☮',
  '🕎',
  '🔯',
  '♈',
  '♉',
  '♊',
  '♋',
  '♌',
  '♍',
  '♎',
  '♏',
  '♐',
  '♑',
  '♒',
  '♓',
  '⛎',
  '🔀',
  '🔁',
  '🔂',
  '▶',
  '⏩',
  '◀',
  '⏪',
  '🔼',
  '⏫',
  '🔽',
  '⏬',
  '⏹',
  '⏏',
  '🎦',
  '🔅',
  '🔆',
  '📶',
  '📳',
  '📴',
  '♾',
  '♻',
  '🔱',
  '📛',
  '🔰',
  '⭕',
  '✅',
  '☑',
  '✔',
  '✖',
  '❌',
  '❎',
  '➕',
  '➖',
  '➗',
  '➰',
  '➿',
  '〽',
  '✳',
  '✴',
  '❇',
  '‼',
  '⁉',
  '❓',
  '❔',
  '❕',
  '❗',
  '©',
  '®',
  '™',
  '#️⃣',
  '0️⃣',
  '1️⃣',
  '2️⃣',
  '3️⃣',
  '4️⃣',
  '5️⃣',
  '6️⃣',
  '7️⃣',
  '8️⃣',
  '9️⃣',
  '🔟',
  '🔠',
  '🔡',
  '🔢',
  '🔣',
  '🔤',
  '🅰',
  '🆎',
  '🅱',
  '🆑',
  '🆒',
  '🆓',
  'ℹ',
  '🆔',
  'Ⓜ',
  '🆕',
  '🆖',
  '🅾',
  '🆗',
  '🅿',
  '🆘',
  '🆙',
  '🆚',
  '🈁',
  '🈂',
  '🈷',
  '🈶',
  '🈯',
  '🉐',
  '🈹',
  '🈚',
  '🈲',
  '🉑',
  '🈸',
  '🈴',
  '🈳',
  '㊗',
  '㊙',
  '🈺',
  '🈵',
  '🔴',
  '🔵',
  '⚫',
  '⚪',
  '⬛',
  '⬜',
  '◼',
  '◻',
  '◾',
  '◽',
  '▪',
  '▫',
  '🔶',
  '🔷',
  '🔸',
  '🔹',
  '🔺',
  '🔻',
  '💠',
  '🔳',
  '🔲'
]);

/// Map of all possible emojis along with their names in [Category.FLAGS]
final Map<String, String> flags = Map.fromIterables([
  'Chequered Flag',
  'Triangular Flag',
  'Crossed Flags',
  'Black Flag',
  'White Flag',
  'Rainbow Flag',
  'Pirate Flag',
  'Flag: Ascension Island',
  'Flag: Andorra',
  'Flag: United Arab Emirates',
  'Flag: Afghanistan',
  'Flag: Antigua &amp; Barbuda',
  'Flag: Anguilla',
  'Flag: Albania',
  'Flag: Armenia',
  'Flag: Angola',
  'Flag: Antarctica',
  'Flag: Argentina',
  'Flag: American Samoa',
  'Flag: Austria',
  'Flag: Australia',
  'Flag: Aruba',
  'Flag: Åland Islands',
  'Flag: Azerbaijan',
  'Flag: Bosnia &amp; Herzegovina',
  'Flag: Barbados',
  'Flag: Bangladesh',
  'Flag: Belgium',
  'Flag: Burkina Faso',
  'Flag: Bulgaria',
  'Flag: Bahrain',
  'Flag: Burundi',
  'Flag: Benin',
  'Flag: St. Barthélemy',
  'Flag: Bermuda',
  'Flag: Brunei',
  'Flag: Bolivia',
  'Flag: Caribbean Netherlands',
  'Flag: Brazil',
  'Flag: Bahamas',
  'Flag: Bhutan',
  'Flag: Bouvet Island',
  'Flag: Botswana',
  'Flag: Belarus',
  'Flag: Belize',
  'Flag: Canada',
  'Flag: Cocos (Keeling) Islands',
  'Flag: Congo - Kinshasa',
  'Flag: Central African Republic',
  'Flag: Congo - Brazzaville',
  'Flag: Switzerland',
  'Flag: Côte d’Ivoire',
  'Flag: Cook Islands',
  'Flag: Chile',
  'Flag: Cameroon',
  'Flag: China',
  'Flag: Colombia',
  'Flag: Clipperton Island',
  'Flag: Costa Rica',
  'Flag: Cuba',
  'Flag: Cape Verde',
  'Flag: Curaçao',
  'Flag: Christmas Island',
  'Flag: Cyprus',
  'Flag: Czechia',
  'Flag: Germany',
  'Flag: Diego Garcia',
  'Flag: Djibouti',
  'Flag: Denmark',
  'Flag: Dominica',
  'Flag: Dominican Republic',
  'Flag: Algeria',
  'Flag: Ceuta &amp; Melilla',
  'Flag: Ecuador',
  'Flag: Estonia',
  'Flag: Egypt',
  'Flag: Western Sahara',
  'Flag: Eritrea',
  'Flag: Spain',
  'Flag: Ethiopia',
  'Flag: European Union',
  'Flag: Finland',
  'Flag: Fiji',
  'Flag: Falkland Islands',
  'Flag: Micronesia',
  'Flag: Faroe Islands',
  'Flag: France',
  'Flag: Gabon',
  'Flag: United Kingdom',
  'Flag: Grenada',
  'Flag: Georgia',
  'Flag: French Guiana',
  'Flag: Guernsey',
  'Flag: Ghana',
  'Flag: Gibraltar',
  'Flag: Greenland',
  'Flag: Gambia',
  'Flag: Guinea',
  'Flag: Guadeloupe',
  'Flag: Equatorial Guinea',
  'Flag: Greece',
  'Flag: South Georgia &amp; South Sandwich Islands',
  'Flag: Guatemala',
  'Flag: Guam',
  'Flag: Guinea-Bissau',
  'Flag: Guyana',
  'Flag: Hong Kong SAR China',
  'Flag: Heard &amp; McDonald Islands',
  'Flag: Honduras',
  'Flag: Croatia',
  'Flag: Haiti',
  'Flag: Hungary',
  'Flag: Canary Islands',
  'Flag: Indonesia',
  'Flag: Ireland',
  'Flag: Israel',
  'Flag: Isle of Man',
  'Flag: India',
  'Flag: British Indian Ocean Territory',
  'Flag: Iraq',
  'Flag: Iran',
  'Flag: Iceland',
  'Flag: Italy',
  'Flag: Jersey',
  'Flag: Jamaica',
  'Flag: Jordan',
  'Flag: Japan',
  'Flag: Kenya',
  'Flag: Kyrgyzstan',
  'Flag: Cambodia',
  'Flag: Kiribati',
  'Flag: Comoros',
  'Flag: St. Kitts &amp; Nevis',
  'Flag: North Korea',
  'Flag: South Korea',
  'Flag: Kuwait',
  'Flag: Cayman Islands',
  'Flag: Kazakhstan',
  'Flag: Laos',
  'Flag: Lebanon',
  'Flag: St. Lucia',
  'Flag: Liechtenstein',
  'Flag: Sri Lanka',
  'Flag: Liberia',
  'Flag: Lesotho',
  'Flag: Lithuania',
  'Flag: Luxembourg',
  'Flag: Latvia',
  'Flag: Libya',
  'Flag: Morocco',
  'Flag: Monaco',
  'Flag: Moldova',
  'Flag: Montenegro',
  'Flag: St. Martin',
  'Flag: Madagascar',
  'Flag: Marshall Islands',
  'Flag: North Macedonia',
  'Flag: Mali',
  'Flag: Myanmar (Burma)',
  'Flag: Mongolia',
  'Flag: Macau Sar China',
  'Flag: Northern Mariana Islands',
  'Flag: Martinique',
  'Flag: Mauritania',
  'Flag: Montserrat',
  'Flag: Malta',
  'Flag: Mauritius',
  'Flag: Maldives',
  'Flag: Malawi',
  'Flag: Mexico',
  'Flag: Malaysia',
  'Flag: Mozambique',
  'Flag: Namibia',
  'Flag: New Caledonia',
  'Flag: Niger',
  'Flag: Norfolk Island',
  'Flag: Nigeria',
  'Flag: Nicaragua',
  'Flag: Netherlands',
  'Flag: Norway',
  'Flag: Nepal',
  'Flag: Nauru',
  'Flag: Niue',
  'Flag: New Zealand',
  'Flag: Oman',
  'Flag: Panama',
  'Flag: Peru',
  'Flag: French Polynesia',
  'Flag: Papua New Guinea',
  'Flag: Philippines',
  'Flag: Pakistan',
  'Flag: Poland',
  'Flag: St. Pierre &amp; Miquelon',
  'Flag: Pitcairn Islands',
  'Flag: Puerto Rico',
  'Flag: Palestinian Territories',
  'Flag: Portugal',
  'Flag: Palau',
  'Flag: Paraguay',
  'Flag: Qatar',
  'Flag: Réunion',
  'Flag: Romania',
  'Flag: Serbia',
  'Flag: Russia',
  'Flag: Rwanda',
  'Flag: Saudi Arabia',
  'Flag: Solomon Islands',
  'Flag: Seychelles',
  'Flag: Sudan',
  'Flag: Sweden',
  'Flag: Singapore',
  'Flag: St. Helena',
  'Flag: Slovenia',
  'Flag: Svalbard &amp; Jan Mayen',
  'Flag: Slovakia',
  'Flag: Sierra Leone',
  'Flag: San Marino',
  'Flag: Senegal',
  'Flag: Somalia',
  'Flag: Suriname',
  'Flag: South Sudan',
  'Flag: São Tomé &amp; Príncipe',
  'Flag: El Salvador',
  'Flag: Sint Maarten',
  'Flag: Syria',
  'Flag: Swaziland',
  'Flag: Tristan Da Cunha',
  'Flag: Turks &amp; Caicos Islands',
  'Flag: Chad',
  'Flag: French Southern Territories',
  'Flag: Togo',
  'Flag: Thailand',
  'Flag: Tajikistan',
  'Flag: Tokelau',
  'Flag: Timor-Leste',
  'Flag: Turkmenistan',
  'Flag: Tunisia',
  'Flag: Tonga',
  'Flag: Turkey',
  'Flag: Trinidad &amp; Tobago',
  'Flag: Tuvalu',
  'Flag: Taiwan',
  'Flag: Tanzania',
  'Flag: Ukraine',
  'Flag: Uganda',
  'Flag: U.S. Outlying Islands',
  'Flag: United Nations',
  'Flag: United States',
  'Flag: Uruguay',
  'Flag: Uzbekistan',
  'Flag: Vatican City',
  'Flag: St. Vincent &amp; Grenadines',
  'Flag: Venezuela',
  'Flag: British Virgin Islands',
  'Flag: U.S. Virgin Islands',
  'Flag: Vietnam',
  'Flag: Vanuatu',
  'Flag: Wallis &amp; Futuna',
  'Flag: Samoa',
  'Flag: Kosovo',
  'Flag: Yemen',
  'Flag: Mayotte',
  'Flag: South Africa',
  'Flag: Zambia',
  'Flag: Zimbabwe'
], [
  '🏁',
  '🚩',
  '🎌',
  '🏴',
  '🏳',
  '🏳️‍🌈',
  '🏴‍☠️',
  '🇦🇨',
  '🇦🇩',
  '🇦🇪',
  '🇦🇫',
  '🇦🇬',
  '🇦🇮',
  '🇦🇱',
  '🇦🇲',
  '🇦🇴',
  '🇦🇶',
  '🇦🇷',
  '🇦🇸',
  '🇦🇹',
  '🇦🇺',
  '🇦🇼',
  '🇦🇽',
  '🇦🇿',
  '🇧🇦',
  '🇧🇧',
  '🇧🇩',
  '🇧🇪',
  '🇧🇫',
  '🇧🇬',
  '🇧🇭',
  '🇧🇮',
  '🇧🇯',
  '🇧🇱',
  '🇧🇲',
  '🇧🇳',
  '🇧🇴',
  '🇧🇶',
  '🇧🇷',
  '🇧🇸',
  '🇧🇹',
  '🇧🇻',
  '🇧🇼',
  '🇧🇾',
  '🇧🇿',
  '🇨🇦',
  '🇨🇨',
  '🇨🇩',
  '🇨🇫',
  '🇨🇬',
  '🇨🇭',
  '🇨🇮',
  '🇨🇰',
  '🇨🇱',
  '🇨🇲',
  '🇨🇳',
  '🇨🇴',
  '🇨🇵',
  '🇨🇷',
  '🇨🇺',
  '🇨🇻',
  '🇨🇼',
  '🇨🇽',
  '🇨🇾',
  '🇨🇿',
  '🇩🇪',
  '🇩🇬',
  '🇩🇯',
  '🇩🇰',
  '🇩🇲',
  '🇩🇴',
  '🇩🇿',
  '🇪🇦',
  '🇪🇨',
  '🇪🇪',
  '🇪🇬',
  '🇪🇭',
  '🇪🇷',
  '🇪🇸',
  '🇪🇹',
  '🇪🇺',
  '🇫🇮',
  '🇫🇯',
  '🇫🇰',
  '🇫🇲',
  '🇫🇴',
  '🇫🇷',
  '🇬🇦',
  '🇬🇧',
  '🇬🇩',
  '🇬🇪',
  '🇬🇫',
  '🇬🇬',
  '🇬🇭',
  '🇬🇮',
  '🇬🇱',
  '🇬🇲',
  '🇬🇳',
  '🇬🇵',
  '🇬🇶',
  '🇬🇷',
  '🇬🇸',
  '🇬🇹',
  '🇬🇺',
  '🇬🇼',
  '🇬🇾',
  '🇭🇰',
  '🇭🇲',
  '🇭🇳',
  '🇭🇷',
  '🇭🇹',
  '🇭🇺',
  '🇮🇨',
  '🇮🇩',
  '🇮🇪',
  '🇮🇱',
  '🇮🇲',
  '🇮🇳',
  '🇮🇴',
  '🇮🇶',
  '🇮🇷',
  '🇮🇸',
  '🇮🇹',
  '🇯🇪',
  '🇯🇲',
  '🇯🇴',
  '🇯🇵',
  '🇰🇪',
  '🇰🇬',
  '🇰🇭',
  '🇰🇮',
  '🇰🇲',
  '🇰🇳',
  '🇰🇵',
  '🇰🇷',
  '🇰🇼',
  '🇰🇾',
  '🇰🇿',
  '🇱🇦',
  '🇱🇧',
  '🇱🇨',
  '🇱🇮',
  '🇱🇰',
  '🇱🇷',
  '🇱🇸',
  '🇱🇹',
  '🇱🇺',
  '🇱🇻',
  '🇱🇾',
  '🇲🇦',
  '🇲🇨',
  '🇲🇩',
  '🇲🇪',
  '🇲🇫',
  '🇲🇬',
  '🇲🇭',
  '🇲🇰',
  '🇲🇱',
  '🇲🇲',
  '🇲🇳',
  '🇲🇴',
  '🇲🇵',
  '🇲🇶',
  '🇲🇷',
  '🇲🇸',
  '🇲🇹',
  '🇲🇺',
  '🇲🇻',
  '🇲🇼',
  '🇲🇽',
  '🇲🇾',
  '🇲🇿',
  '🇳🇦',
  '🇳🇨',
  '🇳🇪',
  '🇳🇫',
  '🇳🇬',
  '🇳🇮',
  '🇳🇱',
  '🇳🇴',
  '🇳🇵',
  '🇳🇷',
  '🇳🇺',
  '🇳🇿',
  '🇴🇲',
  '🇵🇦',
  '🇵🇪',
  '🇵🇫',
  '🇵🇬',
  '🇵🇭',
  '🇵🇰',
  '🇵🇱',
  '🇵🇲',
  '🇵🇳',
  '🇵🇷',
  '🇵🇸',
  '🇵🇹',
  '🇵🇼',
  '🇵🇾',
  '🇶🇦',
  '🇷🇪',
  '🇷🇴',
  '🇷🇸',
  '🇷🇺',
  '🇷🇼',
  '🇸🇦',
  '🇸🇧',
  '🇸🇨',
  '🇸🇩',
  '🇸🇪',
  '🇸🇬',
  '🇸🇭',
  '🇸🇮',
  '🇸🇯',
  '🇸🇰',
  '🇸🇱',
  '🇸🇲',
  '🇸🇳',
  '🇸🇴',
  '🇸🇷',
  '🇸🇸',
  '🇸🇹',
  '🇸🇻',
  '🇸🇽',
  '🇸🇾',
  '🇸🇿',
  '🇹🇦',
  '🇹🇨',
  '🇹🇩',
  '🇹🇫',
  '🇹🇬',
  '🇹🇭',
  '🇹🇯',
  '🇹🇰',
  '🇹🇱',
  '🇹🇲',
  '🇹🇳',
  '🇹🇴',
  '🇹🇷',
  '🇹🇹',
  '🇹🇻',
  '🇹🇼',
  '🇹🇿',
  '🇺🇦',
  '🇺🇬',
  '🇺🇲',
  '🇺🇳',
  '🇺🇸',
  '🇺🇾',
  '🇺🇿',
  '🇻🇦',
  '🇻🇨',
  '🇻🇪',
  '🇻🇬',
  '🇻🇮',
  '🇻🇳',
  '🇻🇺',
  '🇼🇫',
  '🇼🇸',
  '🇽🇰',
  '🇾🇪',
  '🇾🇹',
  '🇿🇦',
  '🇿🇲',
  '🇿🇼'
]);
